/**
 * G005 放射RIS系统 v3.0.6.11-105 Wave 1C - 质量指标库常量镜像
 *
 * 数据来源 (前端, 零改动镜像):
 *   - src/data/qualityIndicators.ts : 40 条质控指标 (结构 10 / 过程 18 / 结果 12)
 *   - src/data/qualityStandards.ts  : 图像质量评分 / 报告质量标准 14 条 / 检查流程质控点
 * 用途: GET /quality-indicators/extended 与 /quality-indicators/standards 结构化暴露
 */
import type {
  ImageQualityDimension,
  QualityIndicator,
  ReportQualityItem,
  WorkflowQcPoint,
} from './quality-indicators.types'

export const QUALITY_INDICATORS: QualityIndicator[] = [
  // ============ 一、结构类 (10 条) ============
  {
    code: 'QI-S01',
    name: '大型设备年检合格率',
    nameEn: 'Annual inspection pass rate of large equipment',
    category: '结构',
    categoryKey: 'structure',
    formula: '年检合格设备台数 / 在册大型设备台数 × 100%',
    target: '100%',
    frequency: '每年',
    responsible: '设备科 / 技师长',
    threshold: '<100% 立即停机整改',
  },
  {
    code: 'QI-S02',
    name: '设备日常质控执行率',
    nameEn: 'Daily equipment QC execution rate',
    category: '结构',
    categoryKey: 'structure',
    formula: '实际执行质控次数 / 应执行质控次数 × 100%',
    target: '≥98%',
    frequency: '每月',
    responsible: '技师长',
    threshold: '<95% 触发预警',
  },
  {
    code: 'QI-S03',
    name: '放射工作人员持证上岗率',
    nameEn: 'Radiology staff certification rate',
    category: '结构',
    categoryKey: 'structure',
    formula: '持有效上岗证人数 / 在岗放射工作人员数 × 100%',
    target: '100%',
    frequency: '每季度',
    responsible: '人事科 / 科主任',
    threshold: '<100% 禁止独立上岗',
  },
  {
    code: 'QI-S04',
    name: '个人剂量监测覆盖率',
    nameEn: 'Personal dosimetry monitoring coverage',
    category: '结构',
    categoryKey: 'structure',
    formula: '佩戴个人剂量计人数 / 应佩戴放射人员数 × 100%',
    target: '100%',
    frequency: '每季度',
    responsible: '辐射防护小组',
    threshold: '<100% 触发预警',
  },
  {
    code: 'QI-S05',
    name: '防护用品配置达标率',
    nameEn: 'Radiation protection equipment compliance rate',
    category: '结构',
    categoryKey: 'structure',
    formula: '达标机房数 / 机房总数 × 100%',
    target: '≥95%',
    frequency: '每年',
    responsible: '辐射防护小组',
    threshold: '<90% 触发整改',
  },
  {
    code: 'QI-S06',
    name: '检查室环境指标达标率',
    nameEn: 'Examination room environment compliance rate',
    category: '结构',
    categoryKey: 'structure',
    formula: '温湿度/洁净度达标天数 / 考核天数 × 100%',
    target: '≥95%',
    frequency: '每月',
    responsible: '技师组长',
    threshold: '<90% 触发预警',
  },
  {
    code: 'QI-S07',
    name: '危重患者抢救设备完好率',
    nameEn: 'Resuscitation equipment readiness rate',
    category: '结构',
    categoryKey: 'structure',
    formula: '功能完好抢救设备数 / 抢救设备总数 × 100%',
    target: '100%',
    frequency: '每周',
    responsible: '护理组长',
    threshold: '<100% 当日检修',
  },
  {
    code: 'QI-S08',
    name: '制度流程文件完整率',
    nameEn: 'Policy and procedure document completeness',
    category: '结构',
    categoryKey: 'structure',
    formula: '已发布执行文件数 / 应建立文件总数 × 100%',
    target: '100%',
    frequency: '每年',
    responsible: '质控专员',
    threshold: '<100% 限期补齐',
  },
  {
    code: 'QI-S09',
    name: '介入手术授权合格率',
    nameEn: 'Interventional procedure authorization rate',
    category: '结构',
    categoryKey: 'structure',
    formula: '获授权术者人数 / 应授权介入医师数 × 100%',
    target: '100%',
    frequency: '每年',
    responsible: '医务科 / 介入组长',
    threshold: '<100% 禁止独立手术',
  },
  {
    code: 'QI-S10',
    name: '岗位培训完成率',
    nameEn: 'Staff training completion rate',
    category: '结构',
    categoryKey: 'structure',
    formula: '完成年度培训人次 / 应培训人次 × 100%',
    target: '≥95%',
    frequency: '每年',
    responsible: '教学秘书',
    threshold: '<90% 触发预警',
  },
  // ============ 二、过程类 (18 条) ============
  {
    code: 'QI-P01',
    name: '检查申请单规范率',
    nameEn: 'Examination request form compliance rate',
    category: '过程',
    categoryKey: 'process',
    formula: '规范申请单数 / 申请单总数 × 100%',
    target: '≥98%',
    frequency: '每月',
    responsible: '预约登记组长',
    threshold: '<95% 触发预警',
  },
  {
    code: 'QI-P02',
    name: '急诊检查 30 分钟完成率',
    nameEn: 'Emergency exam completion within 30 minutes',
    category: '过程',
    categoryKey: 'process',
    formula: '30 分钟内完成检查例数 / 急诊检查总例数 × 100%',
    target: '≥95%',
    frequency: '每月',
    responsible: '急诊技师组长',
    threshold: '<90% 触发预警',
  },
  {
    code: 'QI-P03',
    name: '平诊检查预约等候时间',
    nameEn: 'Routine exam appointment waiting time',
    category: '过程',
    categoryKey: 'process',
    formula: 'Σ(检查时间-预约时间) / 平诊检查总例数（中位数）',
    target: '≤48 小时',
    frequency: '每月',
    responsible: '预约登记组长',
    threshold: '>72 小时 触发预警',
  },
  {
    code: 'QI-P04',
    name: '检查部位与申请单符合率',
    nameEn: 'Examined body part matches request form',
    category: '过程',
    categoryKey: 'process',
    formula: '部位符合例数 / 抽查总例数 × 100%',
    target: '≥99%',
    frequency: '每月',
    responsible: '审核技师',
    threshold: '<98% 触发预警',
  },
  {
    code: 'QI-P05',
    name: '扫描协议执行准确率',
    nameEn: 'Scan protocol execution accuracy',
    category: '过程',
    categoryKey: 'process',
    formula: '按协议执行例数 / 抽查总例数 × 100%',
    target: '≥98%',
    frequency: '每月',
    responsible: '技师长',
    threshold: '<95% 触发预警',
  },
  {
    code: 'QI-P06',
    name: '对比剂使用适应证符合率',
    nameEn: 'Contrast agent indication compliance rate',
    category: '过程',
    categoryKey: 'process',
    formula: '符合适应证例数 / 增强检查总例数 × 100%',
    target: '≥98%',
    frequency: '每月',
    responsible: '值班医师',
    threshold: '<95% 触发预警',
  },
  {
    code: 'QI-P07',
    name: '对比剂不良反应上报率',
    nameEn: 'Contrast adverse reaction reporting rate',
    category: '过程',
    categoryKey: 'process',
    formula: '实际上报例数 / 发生不良反应总例数 × 100%',
    target: '100%',
    frequency: '每月',
    responsible: '护理组长',
    threshold: '<100% 通报整改',
  },
  {
    code: 'QI-P08',
    name: '图像质量甲级片率',
    nameEn: 'Grade-A image quality rate',
    category: '过程',
    categoryKey: 'process',
    formula: '甲级片数 / 评价片总数 × 100%',
    target: '≥70%',
    frequency: '每月',
    responsible: '质控医师 / 技师长',
    threshold: '<60% 触发预警',
  },
  {
    code: 'QI-P09',
    name: '废片率',
    nameEn: 'Rejected film rate',
    category: '过程',
    categoryKey: 'process',
    formula: '废片数 / 摄片总数 × 100%',
    target: '≤2%',
    frequency: '每月',
    responsible: '技师组长',
    threshold: '>3% 触发预警',
  },
  {
    code: 'QI-P10',
    name: '平诊报告 24 小时出具率',
    nameEn: 'Routine report issued within 24 hours',
    category: '过程',
    categoryKey: 'process',
    formula: '24 小时内出具报告例数 / 平诊报告总例数 × 100%',
    target: '≥95%',
    frequency: '每月',
    responsible: '报告组医师',
    threshold: '<90% 触发预警',
  },
  {
    code: 'QI-P11',
    name: '急诊报告 30 分钟出具率',
    nameEn: 'Emergency report issued within 30 minutes',
    category: '过程',
    categoryKey: 'process',
    formula: '30 分钟内出具报告例数 / 急诊报告总例数 × 100%',
    target: '≥95%',
    frequency: '每月',
    responsible: '急诊报告医师',
    threshold: '<90% 触发预警',
  },
  {
    code: 'QI-P12',
    name: '危急值报告及时率',
    nameEn: 'Timely critical value reporting rate',
    category: '过程',
    categoryKey: 'process',
    formula: '规定时限内报告例数 / 危急值总例数 × 100%',
    target: '100%',
    frequency: '每月',
    responsible: '当班医师',
    threshold: '<100% 即查即改',
  },
  {
    code: 'QI-P13',
    name: '危急值报告记录完整率',
    nameEn: 'Critical value record completeness',
    category: '过程',
    categoryKey: 'process',
    formula: '记录完整例数 / 危急值总例数 × 100%',
    target: '≥98%',
    frequency: '每月',
    responsible: '当班医师',
    threshold: '<95% 触发预警',
  },
  {
    code: 'QI-P14',
    name: '报告审核率（双签名率）',
    nameEn: 'Report review (dual signature) rate',
    category: '过程',
    categoryKey: 'process',
    formula: '双签名报告数 / 报告总例数 × 100%',
    target: '100%',
    frequency: '每月',
    responsible: '审核医师',
    threshold: '<100% 触发预警',
  },
  {
    code: 'QI-P15',
    name: '复查病例图像对比调阅率',
    nameEn: 'Prior image retrieval rate for follow-up cases',
    category: '过程',
    categoryKey: 'process',
    formula: '调阅既往图像例数 / 复查总例数 × 100%',
    target: '≥90%',
    frequency: '每月',
    responsible: '报告医师',
    threshold: '<85% 触发预警',
  },
  {
    code: 'QI-P16',
    name: '患者防护用品佩戴率',
    nameEn: 'Patient radiation protection wearing rate',
    category: '过程',
    categoryKey: 'process',
    formula: '规范佩戴防护用品例数 / 应佩戴例数 × 100%',
    target: '≥98%',
    frequency: '每月',
    responsible: '当班技师',
    threshold: '<95% 触发预警',
  },
  {
    code: 'QI-P17',
    name: '患者辐射剂量记录完整率',
    nameEn: 'Patient radiation dose record completeness',
    category: '过程',
    categoryKey: 'process',
    formula: '完整记录剂量例数 / 检查总例数 × 100%',
    target: '≥99%',
    frequency: '每月',
    responsible: '技师组长',
    threshold: '<98% 触发预警',
  },
  {
    code: 'QI-P18',
    name: '设备操作规范执行率（考核）',
    nameEn: 'Equipment operation standard execution rate',
    category: '过程',
    categoryKey: 'process',
    formula: '考核合格人次 / 考核总人次 × 100%',
    target: '≥98%',
    frequency: '每季度',
    responsible: '技师长',
    threshold: '<95% 需复训',
  },
  // ============ 三、结果类 (12 条) ============
  {
    code: 'QI-R01',
    name: '诊断与病理符合率',
    nameEn: 'Radiology-pathology diagnostic concordance',
    category: '结果',
    categoryKey: 'outcome',
    formula: '影像诊断与病理诊断符合例数 / 有病理对照总例数 × 100%',
    target: '≥90%',
    frequency: '每季度',
    responsible: '科主任',
    threshold: '<85% 触发专项分析',
  },
  {
    code: 'QI-R02',
    name: '影像诊断与手术符合率',
    nameEn: 'Radiology-surgery diagnostic concordance',
    category: '结果',
    categoryKey: 'outcome',
    formula: '与手术结果符合例数 / 有手术对照总例数 × 100%',
    target: '≥90%',
    frequency: '每季度',
    responsible: '科主任',
    threshold: '<85% 触发专项分析',
  },
  {
    code: 'QI-R03',
    name: '漏诊率（阳性病例）',
    nameEn: 'Missed diagnosis rate (positive cases)',
    category: '结果',
    categoryKey: 'outcome',
    formula: '漏诊阳性例数 / 应诊出阳性总例数 × 100%',
    target: '≤2%',
    frequency: '每季度',
    responsible: '质控医师',
    threshold: '>3% 触发预警',
  },
  {
    code: 'QI-R04',
    name: '误诊率',
    nameEn: 'Misdiagnosis rate',
    category: '结果',
    categoryKey: 'outcome',
    formula: '误诊例数 / 诊断总例数 × 100%',
    target: '≤1%',
    frequency: '每季度',
    responsible: '质控医师',
    threshold: '>2% 触发预警',
  },
  {
    code: 'QI-R05',
    name: '报告修改率（返修率）',
    nameEn: 'Report amendment (rework) rate',
    category: '结果',
    categoryKey: 'outcome',
    formula: '被修改报告数 / 报告总例数 × 100%',
    target: '≤3%',
    frequency: '每月',
    responsible: '质控医师',
    threshold: '>5% 触发预警',
  },
  {
    code: 'QI-R06',
    name: '报告质量抽检评分达标率',
    nameEn: 'Report quality sampling pass rate',
    category: '结果',
    categoryKey: 'outcome',
    formula: '抽检评分≥90 分报告数 / 抽检报告总数 × 100%',
    target: '≥90%',
    frequency: '每月',
    responsible: '质控小组',
    threshold: '<85% 触发预警',
  },
  {
    code: 'QI-R07',
    name: '患者投诉率',
    nameEn: 'Patient complaint rate',
    category: '结果',
    categoryKey: 'outcome',
    formula: '有效投诉例数 / 检查总例数 × 10000（每万例）',
    target: '≤1.5‰（万分之一点五）',
    frequency: '每月',
    responsible: '科主任',
    threshold: '>2‰ 触发预警',
  },
  {
    code: 'QI-R08',
    name: '患者满意度',
    nameEn: 'Patient satisfaction',
    category: '结果',
    categoryKey: 'outcome',
    formula: '满意及非常满意人次 / 调查总人次 × 100%',
    target: '≥95%',
    frequency: '每季度',
    responsible: '护士长',
    threshold: '<90% 触发整改',
  },
  {
    code: 'QI-R09',
    name: '检查取消率（因科室原因）',
    nameEn: 'Exam cancellation rate (departmental causes)',
    category: '结果',
    categoryKey: 'outcome',
    formula: '因科室原因取消例数 / 预约总例数 × 100%',
    target: '≤1%',
    frequency: '每月',
    responsible: '预约登记组长',
    threshold: '>2% 触发预警',
  },
  {
    code: 'QI-R10',
    name: '放射事件发生率',
    nameEn: 'Radiation event incidence',
    category: '结果',
    categoryKey: 'outcome',
    formula: '放射事件（事故/差错）发生起数',
    target: '0 起',
    frequency: '每月',
    responsible: '辐射防护小组',
    threshold: '>0 起 立即启动应急',
  },
  {
    code: 'QI-R11',
    name: '对比剂严重不良反应发生率',
    nameEn: 'Severe contrast adverse reaction incidence',
    category: '结果',
    categoryKey: 'outcome',
    formula: '严重不良反应例数 / 增强检查总例数 × 10000',
    target: '≤1/万',
    frequency: '每季度',
    responsible: '护理组长',
    threshold: '>1/万 触发分析',
  },
  {
    code: 'QI-R12',
    name: '介入手术并发症发生率',
    nameEn: 'Interventional procedure complication rate',
    category: '结果',
    categoryKey: 'outcome',
    formula: '并发症例数 / 介入手术总例数 × 100%',
    target: '≤5%',
    frequency: '每季度',
    responsible: '介入组长',
    threshold: '>8% 触发专项分析',
  },
]

// ============ 图像质量评分标准 (5 维度 × 5 级) ============
export const IMAGE_QUALITY_DIMENSIONS: ImageQualityDimension[] = [
  {
    dimension: '定位准确性',
    dimensionEn: 'Positioning accuracy',
    weight: 0.25,
    levels: [
      { score: 1, levelName: '差', levelNameEn: 'Poor', description: '扫描范围严重偏离目标部位，主要结构缺失，无法诊断', acceptable: false },
      { score: 2, levelName: '较差', levelNameEn: 'Fair', description: '部分目标结构超出扫描范围，需局部补扫', acceptable: false },
      { score: 3, levelName: '一般', levelNameEn: 'Acceptable', description: '目标部位基本包含，边缘结构略有遗漏，不影响主要诊断', acceptable: true },
      { score: 4, levelName: '良好', levelNameEn: 'Good', description: '扫描范围准确完整，定位线符合标准', acceptable: true },
      { score: 5, levelName: '优秀', levelNameEn: 'Excellent', description: '范围精准覆盖病灶，双侧对称，与申请单完全一致', acceptable: true },
    ],
  },
  {
    dimension: '扫描技术参数',
    dimensionEn: 'Scanning parameters',
    weight: 0.2,
    levels: [
      { score: 1, levelName: '差', levelNameEn: 'Poor', description: 'kV/mA/层厚等参数严重错误，图像无法使用', acceptable: false },
      { score: 2, levelName: '较差', levelNameEn: 'Fair', description: '参数设置明显不当（如儿童误用成人剂量）', acceptable: false },
      { score: 3, levelName: '一般', levelNameEn: 'Acceptable', description: '参数基本符合协议，个别细节欠妥', acceptable: true },
      { score: 4, levelName: '良好', levelNameEn: 'Good', description: '参数符合标准协议，重建方案完整（骨窗/软组织窗）', acceptable: true },
      { score: 5, levelName: '优秀', levelNameEn: 'Excellent', description: '按协议执行并针对个体优化（BMI/心率），重建序列齐全', acceptable: true },
    ],
  },
  {
    dimension: '图像清晰度',
    dimensionEn: 'Image sharpness',
    weight: 0.2,
    levels: [
      { score: 1, levelName: '差', levelNameEn: 'Poor', description: '图像严重模糊，解剖结构无法辨认', acceptable: false },
      { score: 2, levelName: '较差', levelNameEn: 'Fair', description: '整体模糊或部分序列模糊，细小结构不可见', acceptable: false },
      { score: 3, levelName: '一般', levelNameEn: 'Acceptable', description: '主要结构清楚，细小结构（微小钙化/细支气管）显示欠佳', acceptable: true },
      { score: 4, levelName: '良好', levelNameEn: 'Good', description: '解剖结构清晰，细小结构可辨', acceptable: true },
      { score: 5, levelName: '优秀', levelNameEn: 'Excellent', description: '极高清图像，微细结构锐利（薄层重建质量佳）', acceptable: true },
    ],
  },
  {
    dimension: '对比度与噪声',
    dimensionEn: 'Contrast and noise',
    weight: 0.2,
    levels: [
      { score: 1, levelName: '差', levelNameEn: 'Poor', description: '噪声过大或对比度严重不足，病灶与周围无法区分', acceptable: false },
      { score: 2, levelName: '较差', levelNameEn: 'Fair', description: '噪声明显或增强效果差（峰值强化<20HU）', acceptable: false },
      { score: 3, levelName: '一般', levelNameEn: 'Acceptable', description: '常规层面可诊断，低对比结构显示一般', acceptable: true },
      { score: 4, levelName: '良好', levelNameEn: 'Good', description: '噪声可接受，增强各期强化满意（峰值>40HU）', acceptable: true },
      { score: 5, levelName: '优秀', levelNameEn: 'Excellent', description: '噪声低、对比度佳，强化时相精准', acceptable: true },
    ],
  },
  {
    dimension: '伪影控制',
    dimensionEn: 'Artifact control',
    weight: 0.15,
    levels: [
      { score: 1, levelName: '差', levelNameEn: 'Poor', description: '伪影致关键区域无法评估，需重扫', acceptable: false },
      { score: 2, levelName: '较差', levelNameEn: 'Fair', description: '明显伪影干扰诊断（运动/金属/呼吸伪影）', acceptable: false },
      { score: 3, levelName: '一般', levelNameEn: 'Acceptable', description: '轻度伪影，不影响主要诊断', acceptable: true },
      { score: 4, levelName: '良好', levelNameEn: 'Good', description: '伪影轻微，对诊断无影响', acceptable: true },
      { score: 5, levelName: '优秀', levelNameEn: 'Excellent', description: '无可见伪影，图像干净', acceptable: true },
    ],
  },
]

// ============ 报告质量标准 (14 条) ============
export const REPORT_QUALITY_STANDARDS: ReportQualityItem[] = [
  {
    id: 'RQ-01',
    category: '结构完整',
    categoryEn: 'Structural completeness',
    item: '报告五要素齐全',
    standard: '患者信息、检查项目、技术参数、影像所见、诊断印象五要素完整',
    checkpoints: ['患者姓名/ID/年龄/性别与申请单一致', '检查方法、部位、对比剂情况完整', '所见段、印象段齐全'],
  },
  {
    id: 'RQ-02',
    category: '结构完整',
    categoryEn: 'Structural completeness',
    item: '诊断印象分层明确',
    standard: '印象段需分层：主要诊断、次要发现、随访建议',
    checkpoints: ['主诊断放首位', '次要发现单列', '随访/复查建议明确'],
  },
  {
    id: 'RQ-03',
    category: '结构完整',
    categoryEn: 'Structural completeness',
    item: '对比既往记录',
    standard: '有既往影像时应说明对比结果（有无变化）',
    checkpoints: ['标注对比时间', '描述病灶变化', '无既往资料时说明'],
  },
  {
    id: 'RQ-04',
    category: '术语规范',
    categoryEn: 'Terminology standard',
    item: '规范术语使用',
    standard: '使用标准影像学术语（含RADS分级），避免口语化描述',
    checkpoints: ['使用标准解剖术语', 'RADS分类规范引用', '避免含糊表达（"好像""似乎"）'],
  },
  {
    id: 'RQ-05',
    category: '术语规范',
    categoryEn: 'Terminology standard',
    item: '左右方位准确',
    standard: '左右、上下、前后方位描述准确且一致',
    checkpoints: ['方位词与图像一致', '多段重复时前后一致', '与临床信息交叉核对'],
  },
  {
    id: 'RQ-06',
    category: '术语规范',
    categoryEn: 'Terminology standard',
    item: '测量规范',
    standard: '病灶需测量大小（三维径线）并标注单位',
    checkpoints: ['三维径线（mm）', '标注测量层面', '随访对比同一层面'],
  },
  {
    id: 'RQ-07',
    category: '描述准确',
    categoryEn: 'Accurate description',
    item: '所见与印象一致性',
    standard: '印象段结论须由所见段征象支持，不得出现前后矛盾',
    checkpoints: ['印象不超出现所见范围', '印象与所见相符', '不确定处注明依据'],
  },
  {
    id: 'RQ-08',
    category: '描述准确',
    categoryEn: 'Accurate description',
    item: '阴性结果完整描述',
    standard: '常规阴性结构应描述，避免漏报',
    checkpoints: ['常规部位阴性描述', '与检查目的相关结构全覆盖', '重要阴性（如无出血）明确'],
  },
  {
    id: 'RQ-09',
    category: '描述准确',
    categoryEn: 'Accurate description',
    item: '危急值报告记录',
    standard: '危急值（气胸、脑出血、主动脉夹层等）需记录电话通知时间及对象',
    checkpoints: ['危急值识别正确', '电话通知记录（时间/接听人）', '报告单标注危急值'],
  },
  {
    id: 'RQ-10',
    category: '诊断明确',
    categoryEn: 'Clear diagnosis',
    item: '结论明确且可执行',
    standard: '印象段结论应明确诊断或给出合理鉴别诊断与建议',
    checkpoints: ['明确诊断给出', '不确定时给出鉴别', '给出下一步建议'],
  },
  {
    id: 'RQ-11',
    category: '诊断明确',
    categoryEn: 'Clear diagnosis',
    item: '分级系统正确使用',
    standard: '肺结节用Lung-RADS、乳腺用BI-RADS、前列腺用PI-RADS等',
    checkpoints: ['分级系统选择正确', '分级依据充分', '随访建议与分级一致'],
  },
  {
    id: 'RQ-12',
    category: '及时性',
    categoryEn: 'Timeliness',
    item: '报告出具时限',
    standard: '急诊30分钟内、平诊2小时内、住院24小时内完成审核',
    checkpoints: ['急诊优先报告', '超时原因登记', '审核人签字'],
  },
  {
    id: 'RQ-13',
    category: '及时性',
    categoryEn: 'Timeliness',
    item: '审核与签署',
    standard: '住院医师报告须主治医师审核，急诊独立值班资格受限',
    checkpoints: ['双签制度', '审核修改留痕', '签名完整'],
  },
  {
    id: 'RQ-14',
    category: '结构完整',
    categoryEn: 'Structural completeness',
    item: '申请单与报告闭环',
    standard: '报告需回应申请单的临床问题',
    checkpoints: ['临床问题针对性回答', '申请单信息核对', '异常结果随访'],
  },
]

// ============ 检查流程质控点 ============
export const WORKFLOW_QC_POINTS: WorkflowQcPoint[] = [
  { id: 'QC-R-01', stage: '登记', stageEn: 'Registration', item: '申请单信息完整', standard: '患者身份、检查部位、临床诊断、检查目的齐全', checkMethod: '核对申请单与挂号信息', responsible: '登记员', onFailure: '退回临床补充' },
  { id: 'QC-R-02', stage: '登记', stageEn: 'Registration', item: '身份核对', standard: '姓名+ID+出生日期双项核对', checkMethod: '询问+腕带/证件核对', responsible: '登记员', onFailure: '禁止检查，查明身份' },
  { id: 'QC-R-03', stage: '登记', stageEn: 'Registration', item: '检查适应症审核', standard: '确认检查符合临床需要，无重复申请', checkMethod: '查询近期检查记录', responsible: '登记员/医师', onFailure: '与开单医师沟通确认' },
  { id: 'QC-R-04', stage: '登记', stageEn: 'Registration', item: '禁忌症筛查', standard: '孕妇、对比剂禁忌、体内金属（MR）筛查', checkMethod: '问诊+筛查表', responsible: '登记员/技师', onFailure: '暂缓检查并报告医师' },
  { id: 'QC-R-05', stage: '登记', stageEn: 'Registration', item: '知情同意（增强）', standard: '增强检查签署知情同意书', checkMethod: '检查签名及日期', responsible: '护士/医师', onFailure: '未签署禁止注射' },
  { id: 'QC-R-06', stage: '登记', stageEn: 'Registration', item: '预约排程合理', standard: '按时段排程，急诊插队有优先级规则', checkMethod: '排程系统记录', responsible: '登记员', onFailure: '超时原因说明' },
  { id: 'QC-E-01', stage: '执行', stageEn: 'Execution', item: '体位与定位', standard: '按协议标准体位，定位像符合解剖要求', checkMethod: '定位像核对', responsible: '技师', onFailure: '重扫定位像' },
  { id: 'QC-E-02', stage: '执行', stageEn: 'Execution', item: '扫描协议选择', standard: '使用标准协议或个体化调整并记录', checkMethod: '协议核对+技师日志', responsible: '技师', onFailure: '按标准协议重新执行' },
  { id: 'QC-E-03', stage: '执行', stageEn: 'Execution', item: '对比剂注射记录', standard: '对比剂种类/剂量/流速/注射时间记录完整', checkMethod: '检查记录单', responsible: '技师/护士', onFailure: '补录记录' },
  { id: 'QC-E-04', stage: '执行', stageEn: 'Execution', item: '辐射防护', standard: '非检查部位铅衣防护；儿童/孕妇优先', checkMethod: '现场观察', responsible: '技师', onFailure: '纠正并记录' },
  { id: 'QC-E-05', stage: '执行', stageEn: 'Execution', item: '患者沟通', standard: '告知检查流程、屏气指令，取得配合', checkMethod: '询问患者', responsible: '技师', onFailure: '强化沟通培训' },
  { id: 'QC-E-06', stage: '执行', stageEn: 'Execution', item: '操作者资质', standard: '独立操作须持证上岗（大型设备上岗证）', checkMethod: '资质档案核对', responsible: '科主任', onFailure: '停止独立操作' },
  { id: 'QC-I-01', stage: '影像', stageEn: 'Imaging', item: '图像完整性', standard: '序列/期相齐全，符合申请要求', checkMethod: '图像清单核对', responsible: '技师/医师', onFailure: '补扫缺失序列' },
  { id: 'QC-I-02', stage: '影像', stageEn: 'Imaging', item: '图像质量初审', standard: '技师离机前初审：定位、伪影、呼吸伪影', checkMethod: '技师自查', responsible: '技师', onFailure: '立即重扫' },
  { id: 'QC-I-03', stage: '影像', stageEn: 'Imaging', item: '影像归档', standard: '图像按时归档PACS，DICOM完整性校验', checkMethod: 'PACS自动校验+人工抽查', responsible: '技师/信息员', onFailure: '重新传输' },
  { id: 'QC-I-04', stage: '影像', stageEn: 'Imaging', item: '危急征象识别', standard: '技师发现危急征象（大量气胸、脑出血等）即时上报医师', checkMethod: '危急值流程核查', responsible: '技师', onFailure: '按危急值处理流程执行' },
  { id: 'QC-I-05', stage: '影像', stageEn: 'Imaging', item: '剂量记录', standard: 'CT检查记录CTDIvol/DLP', checkMethod: '剂量报告核对', responsible: '技师', onFailure: '补录剂量数据' },
  { id: 'QC-P-01', stage: '报告', stageEn: 'Reporting', item: '报告时效', standard: '急诊30分钟、平诊2小时、住院24小时', checkMethod: '系统时限监控', responsible: '报告医师', onFailure: '超时原因登记上报' },
  { id: 'QC-P-02', stage: '报告', stageEn: 'Reporting', item: '双签审核', standard: '初级报告由上级医师审核签发', checkMethod: '审核记录', responsible: '审核医师', onFailure: '未审核不得签发' },
  { id: 'QC-P-03', stage: '报告', stageEn: 'Reporting', item: '报告与图像一致', standard: '报告描述病灶与图像所见相符', checkMethod: '抽样对比复核', responsible: '质控医师', onFailure: '退回修正' },
  { id: 'QC-P-04', stage: '报告', stageEn: 'Reporting', item: '危急值报告', standard: '发现危急值立即电话通知并记录', checkMethod: '危急值登记本+系统', responsible: '报告医师', onFailure: '按危急值制度处理' },
  { id: 'QC-P-05', stage: '报告', stageEn: 'Reporting', item: '报告退回率监控', standard: '月退回率<5%（描述与印象矛盾、漏项）', checkMethod: '质控统计', responsible: '质控组长', onFailure: '针对性培训' },
  { id: 'QC-A-01', stage: '归档', stageEn: 'Archiving', item: '报告发放', standard: '报告电子/纸质发放路径正确，患者可查询', checkMethod: '发放记录', responsible: '登记员', onFailure: '重发并注明' },
  { id: 'QC-A-02', stage: '归档', stageEn: 'Archiving', item: '胶片/光盘发放', standard: '按需打印，标签信息（姓名/ID/部位/日期）完整', checkMethod: '抽查', responsible: '登记员', onFailure: '重新打印' },
  { id: 'QC-A-03', stage: '归档', stageEn: 'Archiving', item: '资料保存期限', standard: '影像资料保存≥15年（X线片≥10年）', checkMethod: '归档系统核查', responsible: '信息员', onFailure: '备份补存' },
]
