apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "g005-ris.fullname" . }}-config
  labels:
    {{- include "g005-ris.labels" . | nindent 4 }}
data:
  {{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
  LOG_LEVEL: info
  BACKUP_DIR: /data/backups
