apiVersion: v1
kind: Service
metadata:
  name: {{ include "g005-ris.fullname" . }}-service
  labels:
    {{- include "g005-ris.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "g005-ris.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: frontend
      protocol: TCP
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendPort }}
