{{- if .Values.ingress.tls }}
{{- range .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    app: g005-ris
type: kubernetes.io/tls
stringData:
  tls.crt: {{ $.Values.secrets.tlsCrt | default "" | quote }}
  tls.key: {{ $.Values.secrets.tlsKey | default "" | quote }}
{{- end }}
{{- end }}
