{{- if and .Values.ingress.tls .Values.tlsSecret.create }}
{{- range .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- include "g005-ris.labels" $ | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ required "tlsSecret.cert is required when tlsSecret.create is true" $.Values.tlsSecret.cert | quote }}
  tls.key: {{ required "tlsSecret.key is required when tlsSecret.create is true" $.Values.tlsSecret.key | quote }}
---
{{- end }}
{{- end }}
