/**
 * G005 鏀惧皠RIS绯荤粺 v3.0.1 - 鍏ㄥ眬璺敱琛ㄤ笌渚ц竟鏍忛厤缃?
 * 浠?v3.0.0 鍗曚綋 App.tsx (768 琛? 鎷嗗嚭,渚夸簬鎸夊煙鍒嗘枃浠剁淮鎶?
 */
import React from "react";
import {
  LayoutDashboard,
  Users,
  CalendarClock,
  Calendar,
  Activity,
  Box,
  Camera,
  FileText,
  ShieldCheck,
  BarChart3,
  ClipboardCheck,
  BookOpen,
  Shield,
  Bell,
  Package,
  Pen,
  ShieldAlert,
  UserCheck,
  GraduationCap,
  UsersRound,
  Database,
  Monitor,
  Radio,
  Cpu,
  Crosshair,
  Printer,
  ListChecks,
  ClipboardList,
  ListOrdered,
  ScrollText,
  FileEdit,
  AlertOctagon,
  MessageSquare,
  TrendingUp,
  DollarSign,
  Gauge,
  FileStack,
  Wrench,
  Settings,
  Leaf,
  Zap,
  Network,
  BarChart2,
  UserCircle,
  History,
  Search,
  Sliders,
  Wand2,
  Download,
  Send,
  Smartphone,
  Stamp,
  Link2,
  Clock,
  Target,
  Award,
  Wallet,
  FileSpreadsheet,
  Edit3,
  Layers,
  GitBranch,
  Eye,
  Image,
  Calculator,
  Sparkles,
} from "lucide-react";
import type { ReactNode } from "react";

export type Role = "医生" | "技师" | "护士" | "管理员" | "主任";

export interface SidebarItem {
  path: string;
  icon: ReactNode;
  labelKey: string;
  roles: ReadonlyArray<Role>;
}

export interface SidebarSection {
  section: string;
  items: ReadonlyArray<SidebarItem>;
}

export const ROLE_NAMES: ReadonlyArray<Role> = [
  "医生",
  "医生",
  "技师",
  "护士",
  "管理员",
  "主任",
];

export const SIDEBAR_ITEMS: ReadonlyArray<SidebarSection> = [
  {
    section: "nav.workbench",
    items: [
      {
        path: "/",
        icon: <LayoutDashboard size={18} />,
        labelKey: "nav.homeOverview",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/worklist",
        icon: <ListChecks size={18} />,
        labelKey: "nav.worklist",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/exams",
        icon: <ClipboardList size={18} />,
        labelKey: "nav.examRecords",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.patientManagement",
    items: [
      {
        path: "/patients",
        icon: <Users size={18} />,
        labelKey: "nav.patientManage",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/appointments",
        icon: <CalendarClock size={18} />,
        labelKey: "nav.appointment",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/appointment-management",
        icon: <Settings size={18} />,
        labelKey: "nav.appointmentManage",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/queue-call",
        icon: <ListOrdered size={18} />,
        labelKey: "nav.queueCall",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/follow-up",
        icon: <UserCheck size={18} />,
        labelKey: "nav.followUp",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/kiosk/check-in",
        icon: <Smartphone size={18} />,
        labelKey: "nav.kioskCheckIn",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/patient/self-service",
        icon: <UserCircle size={18} />,
        labelKey: "nav.selfServicePortal",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/patient/service-management",
        icon: <Settings size={18} />,
        labelKey: "nav.serviceManagement",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.reportManagement",
    items: [
      {
        path: "/write-report",
        icon: <Edit3 size={18} />,
        labelKey: "nav.writeReport",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/reports/v3-write",
        icon: <Edit3 size={18} />,
        labelKey: "nav.writeReportV3",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/reports",
        icon: <FileText size={18} />,
        labelKey: "nav.reportList",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/critical-value",
        icon: <AlertOctagon size={18} />,
        labelKey: "nav.criticalValue",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/consultation",
        icon: <MessageSquare size={18} />,
        labelKey: "nav.consultation",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/report-review",
        icon: <ClipboardCheck size={18} />,
        labelKey: "nav.reportReview",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/report-revisions",
        icon: <History size={18} />,
        labelKey: "nav.reportRevisions",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/collaboration",
        icon: <Users size={18} />,
        labelKey: "nav.collaboration",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/keyword-check",
        icon: <Search size={18} />,
        labelKey: "nav.keywordCheck",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/report-score-rule",
        icon: <Sliders size={18} />,
        labelKey: "nav.scoreRule",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/report-defect-library",
        icon: <AlertOctagon size={18} />,
        labelKey: "nav.defectLibrary",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/ai-report-draft",
        icon: <Wand2 size={18} />,
        labelKey: "nav.aiReportDraft",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/critical-value-rule",
        icon: <Settings size={18} />,
        labelKey: "nav.cvRule",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/critical-value-stats",
        icon: <BarChart3 size={18} />,
        labelKey: "nav.cvStats",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/special-assessment",
        icon: <Award size={18} />,
        labelKey: "nav.specialAssessment",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/report-export",
        icon: <Download size={18} />,
        labelKey: "nav.reportExport",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/publish",
        icon: <FileStack size={18} />,
        labelKey: "nav.publish",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/report-delivery",
        icon: <Send size={18} />,
        labelKey: "nav.reportDelivery",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/patient-report-portal",
        icon: <Smartphone size={18} />,
        labelKey: "nav.patientPortal",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/ca-signature",
        icon: <Stamp size={18} />,
        labelKey: "nav.caSignature",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/blockchain-proof",
        icon: <Link2 size={18} />,
        labelKey: "nav.blockchainProof",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/cds/management",
        icon: <Sliders size={18} />,
        labelKey: "nav.cdsManagement",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/cds/statistics",
        icon: <BarChart3 size={18} />,
        labelKey: "nav.cdsStatistics",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.qualityControlV3",
    items: [
      {
        path: "/review-center",
        icon: <ClipboardCheck size={18} />,
        labelKey: "nav.reviewCenter",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/quality-control",
        icon: <ShieldCheck size={18} />,
        labelKey: "nav.qualityControlV3",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/critical-value-center",
        icon: <ShieldAlert size={18} />,
        labelKey: "nav.criticalValueCenter",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/defect-management",
        icon: <AlertOctagon size={18} />,
        labelKey: "nav.defectManagement",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-27] 鏀惧皠绉戣川鎺ф€荤湅鏉?(鏂板)
      {
        path: "/qc-dashboard",
        icon: <ShieldCheck size={18} />,
        labelKey: "nav.qcDashboard",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/qc-image",
        icon: <Camera size={18} />,
        labelKey: "nav.qcImage",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/qc-radiologist-annual",
        icon: <Users size={18} />,
        labelKey: "nav.qcRadiologistAnnual",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/cosign",
        icon: <UserCheck size={18} />,
        labelKey: "nav.cosign",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.workflowV3",
    items: [
      {
        path: "/workflow-designer",
        icon: <Layers size={18} />,
        labelKey: "nav.workflowDesigner",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/routing-rules",
        icon: <GitBranch size={18} />,
        labelKey: "nav.routingRules",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/workload-heatmap",
        icon: <BarChart3 size={18} />,
        labelKey: "nav.workloadHeatmap",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/sla-policy",
        icon: <Clock size={18} />,
        labelKey: "nav.slaPolicy",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.imagingPrint",
    items: [
      {
        path: "/dicom-viewer",
        icon: <Activity size={18} />,
        labelKey: "nav.dicomBrowser",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/print-management",
        icon: <Printer size={18} />,
        labelKey: "nav.filmPrint",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/ai-assist",
        icon: <Cpu size={18} />,
        labelKey: "nav.aiAssist",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/vna-dashboard",
        icon: <Database size={18} />,
        labelKey: "nav.vnaDashboard",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.aiIntelligence",
    items: [
      {
        path: "/ai-qc",
        icon: <Zap size={18} />,
        labelKey: "nav.aiQc",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/ai-structured-report",
        icon: <FileText size={18} />,
        labelKey: "nav.aiStructuredReport",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/ai-medical-device",
        icon: <Cpu size={18} />,
        labelKey: "nav.aiMedicalDevice",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.qualityControl",
    items: [
      {
        path: "/qc",
        icon: <ShieldCheck size={18} />,
        labelKey: "nav.imageQc",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/equipment-efficiency",
        icon: <BarChart2 size={18} />,
        labelKey: "nav.equipmentEfficiency",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/typical-cases",
        icon: <GraduationCap size={18} />,
        labelKey: "nav.typicalCases",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/finding-library",
        icon: <Database size={18} />,
        labelKey: "nav.typicalFindings",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/term-library",
        icon: <BookOpen size={18} />,
        labelKey: "nav.reportGlossary",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/template-management",
        icon: <FileStack size={18} />,
        labelKey: "nav.templateManage",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/template-designer",
        icon: <FileStack size={18} />,
        labelKey: "nav.templateDesigner",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/template-inheritance",
        icon: <FileStack size={18} />,
        labelKey: "nav.templateInheritance",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/template-category",
        icon: <FileStack size={18} />,
        labelKey: "nav.templateCategory",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/term-synonym-graph",
        icon: <Network size={18} />,
        labelKey: "nav.termSynonymGraph",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/report-phrase-bank",
        icon: <BookOpen size={18} />,
        labelKey: "nav.phraseBank",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/safety/adverse-events",
        icon: <ShieldAlert size={18} />,
        labelKey: "nav.adverseEvents",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/safety/cqi",
        icon: <TrendingUp size={18} />,
        labelKey: "nav.cqi",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/safety/patient-safety-goals",
        icon: <Target size={18} />,
        labelKey: "nav.patientSafetyGoals",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/safety/radiation-safety",
        icon: <Radio size={18} />,
        labelKey: "nav.radiationSafety",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/safety/rca-analysis",
        icon: <Search size={18} />,
        labelKey: "nav.rcaAnalysis",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/safety/risk-management",
        icon: <Shield size={18} />,
        labelKey: "nav.riskManagement",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.regionalCoordination",
    items: [
      {
        path: "/regional-imaging",
        icon: <Network size={18} />,
        labelKey: "nav.regionalImaging",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/regional-report",
        icon: <FileText size={18} />,
        labelKey: "nav.regionalReport",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/schedule",
        icon: <CalendarClock size={18} />,
        labelKey: "nav.departmentSchedule",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/department",
        icon: <UsersRound size={18} />,
        labelKey: "nav.departmentManage",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/hie/medical-alliance",
        icon: <Network size={18} />,
        labelKey: "nav.medicalAlliance",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/integration/fhir-server",
        icon: <Network size={18} />,
        labelKey: "nav.fhirServer",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/integration/ihe-connectathon",
        icon: <Network size={18} />,
        labelKey: "nav.iheConnectathon",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/integration/mllp-monitor",
        icon: <Network size={18} />,
        labelKey: "nav.mllpMonitor",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.patientService",
    items: [
      {
        path: "/cancer-screen",
        icon: <Shield size={18} />,
        labelKey: "nav.cancerScreen",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/patient-portal",
        icon: <UserCircle size={18} />,
        labelKey: "nav.patientImageQuery",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/clinical-data",
        icon: <Database size={18} />,
        labelKey: "nav.clinicalData",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/education/patient-education",
        icon: <BookOpen size={18} />,
        labelKey: "nav.patientEducation",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/mobile/patient",
        icon: <Smartphone size={18} />,
        labelKey: "nav.patientMobileApp",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/mobile/doctor",
        icon: <Smartphone size={18} />,
        labelKey: "nav.doctorMobileWorkstation",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/mobile/nurse",
        icon: <Smartphone size={18} />,
        labelKey: "nav.nurseMobileWorkstation",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/mobile/tech",
        icon: <Smartphone size={18} />,
        labelKey: "nav.techMobileWorkstation",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.dataAnalysis",
    items: [
      {
        path: "/statistics",
        icon: <TrendingUp size={18} />,
        labelKey: "nav.statistics",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/green-it",
        icon: <Leaf size={18} />,
        labelKey: "nav.greenIt",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/department-dashboard",
        icon: <Gauge size={18} />,
        labelKey: "nav.departmentDashboard",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/operations-center",
        icon: <Monitor size={18} />,
        labelKey: "nav.operationsCenter",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/cost-analysis",
        icon: <DollarSign size={18} />,
        labelKey: "nav.costAnalysis",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/stats-report",
        icon: <BarChart3 size={18} />,
        labelKey: "nav.dataStats",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/nuclear-stats",
        icon: <Radio size={18} />,
        labelKey: "nav.nuclearStats",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/report-kpi-dashboard",
        icon: <BarChart3 size={18} />,
        labelKey: "nav.kpiDashboard",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/doctor-workload",
        icon: <Users size={18} />,
        labelKey: "nav.doctorWorkload",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/diagnosis-accuracy",
        icon: <Target size={18} />,
        labelKey: "nav.diagnosisAccuracy",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/report-timeliness",
        icon: <Clock size={18} />,
        labelKey: "nav.reportTimeliness",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/report-search",
        icon: <Search size={18} />,
        labelKey: "nav.reportSearch",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/cardiac/database",
        icon: <Database size={18} />,
        labelKey: "nav.cvDatabase",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/cardiac/operations",
        icon: <Activity size={18} />,
        labelKey: "nav.cvOperations",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/cardiac/qc",
        icon: <ShieldCheck size={18} />,
        labelKey: "nav.cvQc",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/ops/devices",
        icon: <Monitor size={18} />,
        labelKey: "nav.deviceOps",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/ops/hr",
        icon: <Users size={18} />,
        labelKey: "nav.hrOperations",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/ops/dashboard",
        icon: <Gauge size={18} />,
        labelKey: "nav.opsDashboard",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/quality/department",
        icon: <Award size={18} />,
        labelKey: "nav.departmentQuality",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.revenue",
    items: [
      {
        path: "/charge-items",
        icon: <DollarSign size={18} />,
        labelKey: "nav.chargeItems",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/accounts-receivable",
        icon: <Wallet size={18} />,
        labelKey: "nav.accountsReceivable",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/revenue-analysis",
        icon: <BarChart3 size={18} />,
        labelKey: "nav.revenueAnalysis",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/cost-accounting",
        icon: <TrendingUp size={18} />,
        labelKey: "nav.costAccounting",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/financial-reports",
        icon: <FileSpreadsheet size={18} />,
        labelKey: "nav.financialReports",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.dataReport",
    items: [
      {
        path: "/national-report",
        icon: <ShieldAlert size={18} />,
        labelKey: "nav.nationalReport",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/data-report-center",
        icon: <Database size={18} />,
        labelKey: "nav.dataReportCenter",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/insurance-audit",
        icon: <ShieldCheck size={18} />,
        labelKey: "nav.insuranceAudit",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/enterprise-search",
        icon: <Search size={18} />,
        labelKey: "nav.enterpriseSearch",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.eyeSpecialty",
    items: [
      {
        path: "/eye",
        icon: <Eye size={18} />,
        labelKey: "nav.eyeWorkspace",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/pacs",
        icon: <Image size={18} />,
        labelKey: "nav.eyePacs",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/pacs/fundus",
        icon: <Eye size={18} />,
        labelKey: "nav.eyeFundus",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/pacs/oct",
        icon: <Eye size={18} />,
        labelKey: "nav.eyeOct",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/pacs/oct-a",
        icon: <Image size={18} />,
        labelKey: "nav.eyeOcta",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/pacs/visual-field",
        icon: <Activity size={18} />,
        labelKey: "nav.eyeVisualField",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/pacs/topography",
        icon: <Image size={18} />,
        labelKey: "nav.eyeTopography",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/pacs/ffa",
        icon: <Image size={18} />,
        labelKey: "nav.eyeFfa",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/pacs/compare",
        icon: <Activity size={18} />,
        labelKey: "nav.eyeCompare",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/pacs/montage",
        icon: <Image size={18} />,
        labelKey: "nav.eyeMontage",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/ris",
        icon: <Activity size={18} />,
        labelKey: "nav.eyeRis",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/report-write",
        icon: <FileText size={18} />,
        labelKey: "nav.eyeReportWrite",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/ris/iol-calculator",
        icon: <Calculator size={18} />,
        labelKey: "nav.eyeIol",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/ris/va",
        icon: <Eye size={18} />,
        labelKey: "nav.eyeVa",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/ris/iop",
        icon: <Activity size={18} />,
        labelKey: "nav.eyeIop",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/emr",
        icon: <BookOpen size={18} />,
        labelKey: "nav.eyeEmr",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/ai",
        icon: <Sparkles size={18} />,
        labelKey: "nav.eyeAi",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/kpi-dashboard",
        icon: <BarChart3 size={18} />,
        labelKey: "nav.eyeKpi",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-85] 琛ラ綈 14 鏉＄溂绉戝鑸?(PR1-PR11)
      {
        path: "/eye/pacs/real-viewer",
        icon: <Image size={18} />,
        labelKey: "nav.eyePacsReal",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/pacs/viewer",
        icon: <Image size={18} />,
        labelKey: "nav.eyePacsViewer",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/ai-report",
        icon: <Sparkles size={18} />,
        labelKey: "nav.eyeAiReport",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/toric-planner",
        icon: <Calculator size={18} />,
        labelKey: "nav.eyeToric",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/sub/strabismus",
        icon: <Eye size={18} />,
        labelKey: "nav.eyeStrabismus",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/sub/neuro",
        icon: <Activity size={18} />,
        labelKey: "nav.eyeNeuro",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/sub/oncology",
        icon: <Activity size={18} />,
        labelKey: "nav.eyeOncology",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/sub/cornea",
        icon: <Eye size={18} />,
        labelKey: "nav.eyeCornea",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/sub/contact-lens",
        icon: <Eye size={18} />,
        labelKey: "nav.eyeContactLens",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/sub/low-vision",
        icon: <Eye size={18} />,
        labelKey: "nav.eyeLowVision",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/sub/cataract",
        icon: <Eye size={18} />,
        labelKey: "nav.eyeCataract",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/sub/refractive",
        icon: <Eye size={18} />,
        labelKey: "nav.eyeRefractive",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/tele",
        icon: <Activity size={18} />,
        labelKey: "nav.eyeTele",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/case-library",
        icon: <BookOpen size={18} />,
        labelKey: "nav.eyeCaseLibrary",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/eye/optometry-loop",
        icon: <Activity size={18} />,
        labelKey: "nav.eyeOptometryLoop",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  // [v3.0.6.8-54] 鍙ｈ厰涓撶
  {
    section: "nav.dentalSpecialty",
    items: [
      {
        path: "/dental",
        icon: React.createElement(Activity, { size: 18 }),
        labelKey: "nav.dentalWorkspace",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dental/studies",
        icon: React.createElement(Activity, { size: 18 }),
        labelKey: "nav.dentalPacs",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dental/chart",
        icon: React.createElement(Activity, { size: 18 }),
        labelKey: "nav.dentalChart",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dental/ai",
        icon: React.createElement(Activity, { size: 18 }),
        labelKey: "nav.dentalAi",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dental/treatment",
        icon: React.createElement(Activity, { size: 18 }),
        labelKey: "nav.dentalTreatment",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dental/implant",
        icon: React.createElement(Activity, { size: 18 }),
        labelKey: "nav.dentalImplant",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dental/ortho",
        icon: React.createElement(Activity, { size: 18 }),
        labelKey: "nav.dentalOrtho",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dental/tele",
        icon: React.createElement(Activity, { size: 18 }),
        labelKey: "nav.dentalTele",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dental/inventory",
        icon: React.createElement(Activity, { size: 18 }),
        labelKey: "nav.dentalInventory",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dental/dashboard",
        icon: React.createElement(BarChart3, { size: 18 }),
        labelKey: "nav.dentalDashboard",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-87] Phase 1: 淇 CAD/CAM
      {
        path: "/dental/cad",
        icon: React.createElement(Pen, { size: 18 }),
        labelKey: "nav.dentalCad",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-88] Phase 1: 绉嶆 3D 瑙勫垝
      {
        path: "/dental/implant-3d",
        icon: React.createElement(Box, { size: 18 }),
        labelKey: "nav.dentalImplant3d",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-89] Phase 1: 瀵兼澘 + 涓婇儴
      {
        path: "/dental/guide",
        icon: React.createElement(Layers, { size: 18 }),
        labelKey: "nav.dentalGuide",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-90] Phase 2: 澶村奖娴嬮噺
      {
        path: "/dental/ceph",
        icon: React.createElement(Crosshair, { size: 18 }),
        labelKey: "nav.dentalCeph",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-92] Phase 2: 闅愬舰鐭不
      {
        path: "/dental/aligner",
        icon: React.createElement(Layers, { size: 18 }),
        labelKey: "nav.dentalAligner",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-93] Phase 3: CBCT 浣撴覆鏌?
      {
        path: "/dental/volume-viewer",
        icon: React.createElement(Box, { size: 18 }),
        labelKey: "nav.dentalVolume",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-94] Phase 4: 360掳 鎮ｈ€呰鍥?
      {
        path: "/dental/patient-view",
        icon: React.createElement(Users, { size: 18 }),
        labelKey: "nav.dentalEmr",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-95] Phase 4: 鏀惰垂/鍒掍环
      {
        path: "/dental/billing",
        icon: React.createElement(DollarSign, { size: 18 }),
        labelKey: "nav.dentalBilling",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-96] Phase 4: 鎺掔彮+PSR
      {
        path: "/dental/schedule",
        icon: React.createElement(Calendar, { size: 18 }),
        labelKey: "nav.dentalSchedule",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      // [v3.0.6.8-98] Phase 5: 鍙ｅ唴鐓х墖
      {
        path: "/dental/photo",
        icon: React.createElement(Camera, { size: 18 }),
        labelKey: "nav.dentalPhoto",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.systemManage",
    items: [
      {
        path: "/user-management",
        icon: <Shield size={18} />,
        labelKey: "nav.userManagement",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/admin/config",
        icon: <Sliders size={18} />,
        labelKey: "nav.clinicalConfig",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dictionary",
        icon: <BookOpen size={18} />,
        labelKey: "nav.dataDictionary",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/operation-log",
        icon: <ScrollText size={18} />,
        labelKey: "nav.operationLog",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/notification-center",
        icon: <Bell size={18} />,
        labelKey: "nav.notification",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/system/dicom-print",
        icon: <Printer size={18} />,
        labelKey: "nav.dicomPrint",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/business-continuity",
        icon: <Shield size={18} />,
        labelKey: "nav.businessContinuity",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/multi-site",
        icon: <Network size={18} />,
        labelKey: "nav.multiSiteDashboard",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/cloud-storage",
        icon: <Database size={18} />,
        labelKey: "nav.cloudStorage",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/finance/department",
        icon: <DollarSign size={18} />,
        labelKey: "nav.departmentFinance",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/finance/patient",
        icon: <Wallet size={18} />,
        labelKey: "nav.patientFinance",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
  {
    section: "nav.equipmentMaterials",
    items: [
      {
        path: "/equipment-lifecycle",
        icon: <Cpu size={18} />,
        labelKey: "nav.equipmentLifecycle",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/devices",
        icon: <Monitor size={18} />,
        labelKey: "nav.devices",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/device-fault",
        icon: <Wrench size={18} />,
        labelKey: "nav.faultRegister",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/materials",
        icon: <Package size={18} />,
        labelKey: "nav.materialsManage",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/dose-track",
        icon: <Activity size={18} />,
        labelKey: "nav.doseTrack",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/contrast/adverse-reactions",
        icon: <AlertOctagon size={18} />,
        labelKey: "nav.adverseReactions",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/contrast/injection-workstation",
        icon: <Monitor size={18} />,
        labelKey: "nav.injectionWorkstation",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/contrast/inventory",
        icon: <Package size={18} />,
        labelKey: "nav.contrastInventory",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
      {
        path: "/contrast/quality-compliance",
        icon: <ShieldCheck size={18} />,
        labelKey: "nav.contrastQualityCompliance",
        roles: ["医生", "技师", "护士", "管理员", "主任"],
      },
    ],
  },
];
