// ============ 模拟数据 ============

import type {
  AAPMReference,
  MonthlyDoseTrend,
  DeviceDoseData,
  PatientDoseRecord,
  DoseAlert,
  CumulativeStats,
  BreastDoseRecord,
  PediatricDoseRecord,
  DICOMSRRecord,
  CumulativeDosePoint,
  StaffDoseRecord,
  DRLRecord,
  ControlChartPoint,
  PediatricProtocol,
} from './types';

// AAPM/欧盟CT剂量参考值
export const AAPM_EU_REFERENCES: AAPMReference[] = [
  { examType: "头部CT", aapmRef: 56, euRef: 60, hospitalAvg: 52, exceedRate: 0 },
  { examType: "胸部CT", aapmRef: 15, euRef: 10, hospitalAvg: 18, exceedRate: 0.8 },
  { examType: "腹部CT", aapmRef: 25, euRef: 15, hospitalAvg: 28, exceedRate: 0.87 },
  { examType: "盆腔CT", aapmRef: 20, euRef: 18, hospitalAvg: 22, exceedRate: 0.5 },
  { examType: "脊柱CT", aapmRef: 30, euRef: 28, hospitalAvg: 25, exceedRate: 0 },
  { examType: "冠脉CTA", aapmRef: 50, euRef: 45, hospitalAvg: 48, exceedRate: 0.3 },
];
export const doseHistoryData = [
  { date: "04-25", CT: 1250, MR: 0, DR: 180, DSA: 420, MG: 8 },
  { date: "04-26", CT: 1180, MR: 0, DR: 195, DSA: 380, MG: 6 },
  { date: "04-27", CT: 1320, MR: 0, DR: 210, DSA: 450, MG: 10 },
  { date: "04-28", CT: 1190, MR: 0, DR: 175, DSA: 0, MG: 4 },
  { date: "04-29", CT: 980, MR: 0, DR: 120, DSA: 400, MG: 8 },
  { date: "04-30", CT: 1100, MR: 0, DR: 160, DSA: 390, MG: 12 },
  { date: "05-01", CT: 850, MR: 0, DR: 95, DSA: 200, MG: 4 },
];

// CTDIvol趋势数据
export const ctdivolTrendData = [
  { date: "04-25", CT1: 22.5, CT2: 18.2, threshold: 50 },
  { date: "04-26", CT1: 21.8, CT2: 17.5, threshold: 50 },
  { date: "04-27", CT1: 24.2, CT2: 19.8, threshold: 50 },
  { date: "04-28", CT1: 20.5, CT2: 16.8, threshold: 50 },
  { date: "04-29", CT1: 18.9, CT2: 15.2, threshold: 50 },
  { date: "04-30", CT1: 23.1, CT2: 18.9, threshold: 50 },
  { date: "05-01", CT1: 19.5, CT2: 14.8, threshold: 50 },
];

// 设备DAP对比数据
export const deviceDAPComparison = [
  { device: "CT-1", DAP: 850, threshold: 1000, avgDAP: 720 },
  { device: "CT-2", DAP: 620, threshold: 1000, avgDAP: 680 },
  { device: "DR-1", DAP: 95, threshold: 300, avgDAP: 85 },
  { device: "DR-2", DAP: 78, threshold: 300, avgDAP: 72 },
  { device: "DSA-1", DAP: 4200, threshold: 3000, avgDAP: 3500 },
  { device: "MG-1", DAP: 8, threshold: 10, avgDAP: 7.2 },
];

// 月度剂量趋势数据
export const monthlyDoseTrend: MonthlyDoseTrend[] = [
  {
    month: "2025-07",
    ctAvgDLP: 820,
    chestCTAvgDLP: 580,
    abdomenCTAvgDLP: 950,
    headCTAvgDLP: 720,
  },
  {
    month: "2025-08",
    ctAvgDLP: 805,
    chestCTAvgDLP: 560,
    abdomenCTAvgDLP: 920,
    headCTAvgDLP: 710,
  },
  {
    month: "2025-09",
    ctAvgDLP: 790,
    chestCTAvgDLP: 540,
    abdomenCTAvgDLP: 880,
    headCTAvgDLP: 695,
  },
  {
    month: "2025-10",
    ctAvgDLP: 775,
    chestCTAvgDLP: 520,
    abdomenCTAvgDLP: 850,
    headCTAvgDLP: 680,
  },
  {
    month: "2025-11",
    ctAvgDLP: 760,
    chestCTAvgDLP: 500,
    abdomenCTAvgDLP: 820,
    headCTAvgDLP: 665,
  },
  {
    month: "2025-12",
    ctAvgDLP: 745,
    chestCTAvgDLP: 480,
    abdomenCTAvgDLP: 790,
    headCTAvgDLP: 650,
  },
  {
    month: "2026-01",
    ctAvgDLP: 730,
    chestCTAvgDLP: 460,
    abdomenCTAvgDLP: 760,
    headCTAvgDLP: 635,
  },
  {
    month: "2026-02",
    ctAvgDLP: 718,
    chestCTAvgDLP: 445,
    abdomenCTAvgDLP: 740,
    headCTAvgDLP: 620,
  },
  {
    month: "2026-03",
    ctAvgDLP: 705,
    chestCTAvgDLP: 430,
    abdomenCTAvgDLP: 720,
    headCTAvgDLP: 605,
  },
  {
    month: "2026-04",
    ctAvgDLP: 695,
    chestCTAvgDLP: 415,
    abdomenCTAvgDLP: 700,
    headCTAvgDLP: 590,
  },
];

// 设备换装前后对比数据
export const equipmentUpgradeComparison = [
  {
    period: "placeholder",
    ct1AvgDLP: 920,
    ct2AvgDLP: 880,
    hospitalAvgDLP: 900,
  },
  {
    period: "placeholder",
    ct1AvgDLP: 720,
    ct2AvgDLP: 680,
    hospitalAvgDLP: 695,
  },
];

export const deviceDoseData: DeviceDoseData[] = [
  {
    device: "CT-1",
    todayDLP: 850,
    todayCTDI: 22.5,
    todayDAP: 850,
    alertCount: 2,
    status: "normal",
    examCount: 28,
    utilizationRate: 85,
    avgCTDI: 21.2,
    maxCTDI: 28.5,
  },
  {
    device: "CT-2",
    todayDLP: 620,
    todayCTDI: 18.2,
    todayDAP: 620,
    alertCount: 0,
    status: "normal",
    examCount: 22,
    utilizationRate: 72,
    avgCTDI: 17.5,
    maxCTDI: 22.3,
  },
  {
    device: "DR-1",
    todayDLP: 95,
    todayCTDI: 0.8,
    todayDAP: 95,
    alertCount: 0,
    status: "normal",
    examCount: 45,
    utilizationRate: 90,
    avgCTDI: 0.75,
    maxCTDI: 1.2,
  },
  {
    device: "DR-2",
    todayDLP: 78,
    todayCTDI: 0.6,
    todayDAP: 78,
    alertCount: 0,
    status: "normal",
    examCount: 38,
    utilizationRate: 78,
    avgCTDI: 0.62,
    maxCTDI: 0.95,
  },
  {
    device: "DSA-1",
    todayDLP: 4200,
    todayCTDI: 35.8,
    todayDAP: 4200,
    alertCount: 3,
    status: "warning",
    examCount: 8,
    utilizationRate: 45,
    avgCTDI: 32.5,
    maxCTDI: 48.2,
  },
  {
    device: "MG-1",
    todayDLP: 8,
    todayCTDI: 0.4,
    todayDAP: 8,
    alertCount: 0,
    status: "normal",
    examCount: 18,
    utilizationRate: 65,
    avgCTDI: 0.38,
    maxCTDI: 0.52,
  },
];

export const patientDoseRecords: PatientDoseRecord[] = [
  {
    id: "DDR001",
    patientId: "RAD-P001",
patientName: "患者A",
gender: "男",
    age: 62,
    modality: "CT",
    examItem: "冠脉CTA",
    examDate: "2026-05-01",
    doseType: "DLP",
    doseValue: 856,
    doseUnit: "mGy路cm",
    alertLevel: "warning",
    threshold: 800,
    device: "CT-1",
    examCount: 5,
    cumulativeDLP: 4200,
  },
  {
    id: "DDR002",
    patientId: "RAD-P004",
patientName: "患者B",
gender: "女",
    age: 45,
    modality: "CT",
    examItem: "胸部CT",
    examDate: "2026-05-01",
    doseType: "DLP",
    doseValue: 680,
    doseUnit: "mGy路cm",
    alertLevel: "normal",
    threshold: 800,
    device: "CT-2",
    examCount: 2,
    cumulativeDLP: 1250,
  },
  {
    id: "DDR003",
    patientId: "RAD-P005",
patientName: "患者C",
gender: "男",
    age: 52,
    modality: "CT",
    examItem: "腹部CT增强",
    examDate: "2026-05-01",
    doseType: "DLP",
    doseValue: 1250,
    doseUnit: "mGy路cm",
    alertLevel: "critical",
    threshold: 1000,
    device: "CT-2",
    examCount: 3,
    cumulativeDLP: 2800,
  },
  {
    id: "DDR004",
    patientId: "RAD-P001",
patientName: "患者D",
gender: "女",
    age: 62,
    modality: "DSA",
    examItem: "冠脉造影",
    examDate: "2026-04-28",
    doseType: "DAP",
    doseValue: 3850,
    doseUnit: "mGy路m虏",
    alertLevel: "critical",
    threshold: 3000,
    device: "DSA-1",
    examCount: 12,
    cumulativeDLP: 15000,
  },
  {
    id: "DDR005",
    patientId: "RAD-P007",
    patientName: "张伟",
gender: "男",
    age: 42,
    modality: "乳腺钼靶",
    examItem: "乳腺钼靶",
    examDate: "2026-05-01",
    doseType: "AGD",
    doseValue: 4.2,
    doseUnit: "mGy",
    alertLevel: "normal",
    threshold: 6,
    device: "MG-1",
    examCount: 1,
    cumulativeDLP: 4.2,
  },
  {
    id: "DDR006",
    patientId: "RAD-P003",
patientName: "患者E",
gender: "女",
    age: 58,
    modality: "DR",
examItem: "CT检查",
    examDate: "2026-05-01",
    doseType: "DAP",
    doseValue: 0.15,
    doseUnit: "mGy路m虏",
    alertLevel: "normal",
    threshold: 1,
    device: "DR-1",
    examCount: 8,
    cumulativeDLP: 1.2,
  },
  {
    id: "DDR007",
    patientId: "RAD-P008",
patientName: "患者F",
gender: "男",
    age: 68,
    modality: "CT",
    examItem: "胸部CT平扫",
    examDate: "2026-05-01",
    doseType: "DLP",
    doseValue: 580,
    doseUnit: "mGy路cm",
    alertLevel: "normal",
    threshold: 600,
    device: "CT-1",
    examCount: 4,
    cumulativeDLP: 2100,
  },
  {
    id: "DDR008",
    patientId: "RAD-P009",
patientName: "患者G",
gender: "女",
    age: 55,
    modality: "DSA",
    examItem: "头部CT",
    examDate: "2026-04-30",
    doseType: "DAP",
    doseValue: 2650,
    doseUnit: "mGy路m虏",
    alertLevel: "warning",
    threshold: 2500,
    device: "DSA-1",
    examCount: 6,
    cumulativeDLP: 8500,
  },
  {
    id: "DDR009",
    patientId: "RAD-P010",
patientName: "患者H",
gender: "男",
    age: 8,
    modality: "CT",
    examItem: "头部CT",
    examDate: "2026-05-01",
    doseType: "DLP",
    doseValue: 420,
    doseUnit: "mGy路cm",
    alertLevel: "normal",
    threshold: 560,
    device: "CT-1",
    examCount: 1,
    cumulativeDLP: 420,
    isPediatric: true,
    pediatricAgeGroup: "5-10岁",
  },
  {
    id: "DDR010",
    patientId: "RAD-P011",
patientName: "患者I",
gender: "女",
    age: 5,
    modality: "CT",
    examItem: "胸部CT",
    examDate: "2026-05-01",
    doseType: "DLP",
    doseValue: 280,
    doseUnit: "mGy路cm",
    alertLevel: "normal",
    threshold: 350,
    device: "CT-2",
    examCount: 1,
    cumulativeDLP: 280,
    isPediatric: true,
    pediatricAgeGroup: "11-18岁",
  },
  {
    id: "DDR011",
    patientId: "RAD-P012",
patientName: "患者J",
gender: "男",
    age: 38,
    modality: "MG",
    examItem: "乳腺钼靶",
    examDate: "2026-05-01",
    doseType: "AGD",
    doseValue: 5.8,
    doseUnit: "mGy",
    alertLevel: "warning",
    threshold: 6,
    device: "MG-1",
    examCount: 1,
    cumulativeDLP: 5.8,
  },
  {
    id: "DDR012",
    patientId: "RAD-P013",
patientName: "患者K",
gender: "女",
    age: 45,
    modality: "CT",
    examItem: "腹部CT平扫",
    examDate: "2026-04-30",
    doseType: "DLP",
    doseValue: 780,
    doseUnit: "mGy路cm",
    alertLevel: "normal",
    threshold: 800,
    device: "CT-1",
    examCount: 2,
    cumulativeDLP: 1450,
  },
  {
    id: "DDR013",
    patientId: "RAD-P014",
patientName: "患者L",
gender: "男",
    age: 55,
    modality: "CT",
    examItem: "胸部CT增强",
    examDate: "2026-04-30",
    doseType: "DLP",
    doseValue: 950,
    doseUnit: "mGy路cm",
    alertLevel: "warning",
    threshold: 1000,
    device: "CT-2",
    examCount: 2,
    cumulativeDLP: 1800,
  },
  {
    id: "DDR014",
    patientId: "RAD-P015",
patientName: "患者M",
gender: "女",
    age: 12,
    modality: "CT",
    examItem: "腹部CT",
    examDate: "2026-04-30",
    doseType: "DLP",
    doseValue: 320,
    doseUnit: "mGy路cm",
    alertLevel: "normal",
    threshold: 400,
    device: "CT-1",
    examCount: 1,
    cumulativeDLP: 320,
    isPediatric: true,
    pediatricAgeGroup: "3-5岁",
  },
  {
    id: "DDR015",
    patientId: "RAD-P016",
patientName: "患者N",
gender: "男",
    age: 48,
    modality: "MG",
    examItem: "乳腺钼靶",
    examDate: "2026-04-30",
    doseType: "AGD",
    doseValue: 6.5,
    doseUnit: "mGy",
    alertLevel: "critical",
    threshold: 6,
    device: "MG-1",
    examCount: 1,
    cumulativeDLP: 6.5,
  },
];

export const doseAlerts: DoseAlert[] = [
  {
    id: "ALERT001",
patientName: "患者O",
    modality: "CT",
    examItem: "腹部CT增强",
    doseValue: 1250,
    threshold: 1000,
    alertLevel: "critical",
    device: "CT-2",
    time: "2026-05-01 14:30",
    status: "pending",
  },
  {
    id: "ALERT002",
patientName: "患者P",
    modality: "DSA",
    examItem: "冠脉造影",
    doseValue: 3850,
    threshold: 3000,
    alertLevel: "critical",
    device: "DSA-1",
    time: "2026-04-28 11:20",
    status: "acknowledged",
    notes: "placeholder",
  },
  {
    id: "ALERT003",
patientName: "患者Q",
    modality: "CT",
    examItem: "冠脉CTA",
    doseValue: 856,
    threshold: 800,
    alertLevel: "warning",
    device: "CT-1",
    time: "2026-05-01 09:45",
    status: "pending",
  },
  {
    id: "ALERT004",
patientName: "患者R",
    modality: "DSA",
    examItem: "冠脉CTA",
    doseValue: 2650,
    threshold: 2500,
    alertLevel: "warning",
    device: "DSA-1",
    time: "2026-04-30 16:20",
    status: "pending",
  },
  {
    id: "ALERT005",
patientName: "患者S",
    modality: "MG",
    examItem: "乳腺钼靶",
    doseValue: 6.5,
    threshold: 6,
    alertLevel: "critical",
    device: "MG-1",
    time: "2026-04-30 10:15",
    status: "pending",
  },
];

export const cumulativeStats: CumulativeStats = {
  totalPatientsToday: 247,
  highDosePatients: 8,
  totalDLPToday: 2865,
  doseAlertsToday: 5,
  averageDLP: { CT: 720, DR: 0.12, DSA: 2800, MG: 3.8 },
  totalExamCount: 312,
  criticalAlerts: 2,
  warningAlerts: 3,
  deviceOnlineCount: 6,
  averageCTDIvol: 18.5,
  doseReductionRate: 5.2,
};

// 乳腺剂量追踪数据
export const breastDoseRecords: BreastDoseRecord[] = [
  {
    id: "B001",
    patientId: "RAD-P007",
    patientName: "王芳",
    age: 42,
    examDate: "2026-05-01",
    agd: 4.2,
    doseUnit: "mGy",
    referenceValue: 6,
    alertLevel: "normal",
    recallStatus: "none",
    device: "MG-1",
  },
  {
    id: "B002",
    patientId: "RAD-P012",
patientName: "患者T",
    age: 38,
    examDate: "2026-05-01",
    agd: 5.8,
    doseUnit: "mGy",
    referenceValue: 6,
    alertLevel: "warning",
    recallStatus: "none",
    device: "MG-1",
  },
  {
    id: "B003",
    patientId: "RAD-P016",
patientName: "患者A",
    age: 48,
    examDate: "2026-04-30",
    agd: 6.5,
    doseUnit: "mGy",
    referenceValue: 6,
    alertLevel: "critical",
    recallStatus: "recalled",
    device: "MG-1",
  },
  {
    id: "B004",
    patientId: "RAD-P020",
patientName: "患者B",
    age: 52,
    examDate: "2026-04-29",
    agd: 3.8,
    doseUnit: "mGy",
    referenceValue: 6,
    alertLevel: "normal",
    recallStatus: "none",
    device: "MG-1",
  },
  {
    id: "B005",
    patientId: "RAD-P021",
patientName: "患者C",
    age: 45,
    examDate: "2026-04-29",
    agd: 4.5,
    doseUnit: "mGy",
    referenceValue: 6,
    alertLevel: "normal",
    recallStatus: "none",
    device: "MG-1",
  },
  {
    id: "B006",
    patientId: "RAD-P022",
patientName: "患者D",
    age: 55,
    examDate: "2026-04-28",
    agd: 5.2,
    doseUnit: "mGy",
    referenceValue: 6,
    alertLevel: "normal",
    recallStatus: "none",
    device: "MG-1",
  },
  {
    id: "B007",
    patientId: "RAD-P023",
    patientName: "刘芳",
    age: 40,
    examDate: "2026-04-28",
    agd: 4.8,
    doseUnit: "mGy",
    referenceValue: 6,
    alertLevel: "normal",
    recallStatus: "none",
    device: "MG-1",
  },
  {
    id: "B008",
    patientId: "RAD-P024",
patientName: "患者E",
    age: 50,
    examDate: "2026-04-27",
    agd: 6.2,
    doseUnit: "mGy",
    referenceValue: 6,
    alertLevel: "critical",
    recallStatus: "completed",
    device: "MG-1",
  },
];

// 儿童剂量追踪数据
export const pediatricDoseRecords: PediatricDoseRecord[] = [
  {
    id: "P001",
    patientId: "RAD-P010",
patientName: "患者F",
    age: 8,
    ageGroup: "placeholder",
gender: "女",
    examDate: "2026-05-01",
    modality: "CT",
    examItem: "头部CT",
    doseValue: 420,
    doseUnit: "mGy路cm",
    doseReductionFactor: 0.6,
    alertLevel: "normal",
    device: "CT-1",
  },
  {
    id: "P002",
    patientId: "RAD-P011",
patientName: "患者G",
    age: 5,
    ageGroup: "placeholder",
gender: "男",
    examDate: "2026-05-01",
    modality: "CT",
    examItem: "胸部CT",
    doseValue: 280,
    doseUnit: "mGy路cm",
    doseReductionFactor: 0.4,
    alertLevel: "normal",
    device: "CT-2",
  },
  {
    id: "P003",
    patientId: "RAD-P015",
patientName: "患者H",
    age: 12,
    ageGroup: "placeholder",
gender: "女",
    examDate: "2026-04-30",
    modality: "CT",
    examItem: "乳腺钼靶",
    doseValue: 320,
    doseUnit: "mGy路cm",
    doseReductionFactor: 0.7,
    alertLevel: "normal",
    device: "CT-1",
  },
  {
    id: "P004",
    patientId: "RAD-P025",
patientName: "患者I",
    age: 3,
    ageGroup: "placeholder",
gender: "男",
    examDate: "2026-04-30",
    modality: "CT",
    examItem: "腹部CT",
    doseValue: 350,
    doseUnit: "mGy路cm",
    doseReductionFactor: 0.4,
    alertLevel: "normal",
    device: "CT-2",
  },
  {
    id: "P005",
    patientId: "RAD-P026",
patientName: "患者J",
    age: 7,
    ageGroup: "placeholder",
gender: "女",
    examDate: "2026-04-29",
    modality: "CT",
    examItem: "头部CT",
    doseValue: 480,
    doseUnit: "mGy路cm",
    doseReductionFactor: 0.6,
    alertLevel: "warning",
    device: "CT-1",
  },
  {
    id: "P006",
    patientId: "RAD-P027",
patientName: "患者K",
    age: 14,
    ageGroup: "placeholder",
gender: "男",
    examDate: "2026-04-29",
    modality: "CT",
    examItem: "胸部CT",
    doseValue: 380,
    doseUnit: "mGy路cm",
    doseReductionFactor: 0.7,
    alertLevel: "normal",
    device: "CT-2",
  },
];

// DICOM SR 模拟数据
export const dicomSRRecords: DICOMSRRecord[] = [
  {
    id: "SR001",
patientName: "患者L",
    patientId: "RAD-P001",
    studyDate: "2026-05-01",
    modality: "CT",
    examItem: "冠脉CTA",
    ctdivol: 48.2,
    dlp: 856,
    totalDose: 856,
    doseUnit: "mGy路cm",
    drlReference: 800,
    drlCompliant: false,
    device: "CT-1",
  },
  {
    id: "SR002",
patientName: "患者M",
    patientId: "RAD-P004",
    studyDate: "2026-05-01",
    modality: "CT",
    examItem: "胸部DR",
    ctdivol: 42.5,
    dlp: 680,
    totalDose: 680,
    doseUnit: "mGy路cm",
    drlReference: 800,
    drlCompliant: true,
    device: "CT-2",
  },
  {
    id: "SR003",
patientName: "患者N",
    patientId: "RAD-P003",
    studyDate: "2026-05-01",
    modality: "DR",
examItem: "MRI检查",
    ctdivol: 0,
    dlp: 0,
    totalDose: 0.15,
    doseUnit: "mGy路m虏",
    drlReference: 0.3,
    drlCompliant: true,
    device: "DR-1",
  },
  {
    id: "SR004",
    patientName: "李娜",
    patientId: "RAD-P007",
    studyDate: "2026-05-01",
    modality: "MG",
    examItem: "乳腺钼靶",
    ctdivol: 0,
    dlp: 0,
    totalDose: 4.2,
    doseUnit: "mGy",
    drlReference: 6,
    drlCompliant: true,
    device: "MG-1",
  },
];

// 累计剂量模拟数据
export const cumulativeDoseData: CumulativeDosePoint[] = [
  { date: "2026-01", cumulativeDLP: 850, threshold: 1000, examCount: 3 },
  { date: "2026-02", cumulativeDLP: 1650, threshold: 2000, examCount: 5 },
  { date: "2026-03", cumulativeDLP: 2800, threshold: 3000, examCount: 8 },
  { date: "2026-04", cumulativeDLP: 3500, threshold: 4000, examCount: 10 },
  { date: "2026-05", cumulativeDLP: 4200, threshold: 5000, examCount: 12 },
];

// 工作人员剂量模拟数据
export const staffDoseRecords: StaffDoseRecord[] = [
  {
    id: "S001",
    staffName: "李明",
    department: "placeholder",
    role: "placeholder",
    monthlyDose: 0.85,
    annualDose: 4.2,
    annualLimit: 20,
    doseUnit: "mSv",
    complianceRate: 79,
    readings: [
      { month: "1月", dose: 0.45 },
      { month: "2月", dose: 0.38 },
      { month: "3月", dose: 0.52 },
      { month: "4月", dose: 0.48 },
      { month: "5月", dose: 0.42 },
    ],
  },
  {
    id: "S002",
    staffName: "王芳",
    department: "placeholder",
    role: "放射医师",
    monthlyDose: 0.62,
    annualDose: 3.1,
    annualLimit: 20,
    doseUnit: "mSv",
    complianceRate: 84.5,
    readings: [
      { month: "1月", dose: 0.32 },
      { month: "2月", dose: 0.28 },
      { month: "3月", dose: 0.35 },
      { month: "4月", dose: 0.31 },
      { month: "5月", dose: 0.28 },
    ],
  },
  {
    id: "S003",
    staffName: "张伟",
    department: "placeholder",
    role: "介入医师",
    monthlyDose: 1.85,
    annualDose: 9.2,
    annualLimit: 20,
    doseUnit: "mSv",
    complianceRate: 54,
    readings: [
      { month: "1月", dose: 1.2 },
      { month: "2月", dose: 0.95 },
      { month: "3月", dose: 1.45 },
      { month: "4月", dose: 1.1 },
      { month: "5月", dose: 1.05 },
    ],
  },
  {
    id: "S004",
    staffName: "陈静",
    department: "placeholder",
    role: "placeholder",
    monthlyDose: 0.18,
    annualDose: 0.9,
    annualLimit: 20,
    doseUnit: "mSv",
    complianceRate: 95.5,
    readings: [
      { month: "1月", dose: 0.08 },
      { month: "2月", dose: 0.06 },
      { month: "3月", dose: 0.1 },
      { month: "4月", dose: 0.09 },
      { month: "5月", dose: 0.07 },
    ],
  },
  {
    id: "S005",
    staffName: "刘敏",
    department: "placeholder",
    role: "护师",
    monthlyDose: 0.42,
    annualDose: 2.1,
    annualLimit: 20,
    doseUnit: "mSv",
    complianceRate: 89.5,
    readings: [
      { month: "1月", dose: 0.22 },
      { month: "2月", dose: 0.18 },
      { month: "3月", dose: 0.25 },
      { month: "4月", dose: 0.2 },
      { month: "5月", dose: 0.18 },
    ],
  },
  {
    id: "S006",
    staffName: "赵强",
    department: "placeholder",
    role: "placeholder",
    monthlyDose: 0.55,
    annualDose: 2.8,
    annualLimit: 20,
    doseUnit: "mSv",
    complianceRate: 86,
    readings: [
      { month: "1月", dose: 0.28 },
      { month: "2月", dose: 0.24 },
      { month: "3月", dose: 0.3 },
      { month: "4月", dose: 0.26 },
      { month: "5月", dose: 0.22 },
    ],
  },
];

// DRL配置数据
export const drlRecords: DRLRecord[] = [
  {
    modality: "CT",
    examType: "placeholder",
    nationalDRL: 800,
    localDRL: 750,
    hospitalAvg: 720,
    exceedCount: 12,
    totalCount: 1256,
    compliancePercent: 99,
    unit: "mGy路cm",
  },
  {
    modality: "CT",
    examType: "胸部CT平扫",
    nationalDRL: 600,
    localDRL: 550,
    hospitalAvg: 520,
    exceedCount: 8,
    totalCount: 1089,
    compliancePercent: 99.3,
    unit: "mGy路cm",
  },
  {
    modality: "CT",
    examType: "腹部CT平扫",
    nationalDRL: 800,
    localDRL: 750,
    hospitalAvg: 740,
    exceedCount: 15,
    totalCount: 876,
    compliancePercent: 98.3,
    unit: "mGy路cm",
  },
  {
    modality: "CT",
    examType: "冠脉CTA",
    nationalDRL: 1000,
    localDRL: 950,
    hospitalAvg: 920,
    exceedCount: 22,
    totalCount: 456,
    compliancePercent: 95.2,
    unit: "mGy路cm",
  },
  {
    modality: "DR",
    examType: "placeholder",
    nationalDRL: 0.3,
    localDRL: 0.28,
    hospitalAvg: 0.25,
    exceedCount: 0,
    totalCount: 2156,
    compliancePercent: 100,
    unit: "mGy路m虏",
  },
  {
    modality: "DSA",
    examType: "冠脉造影",
    nationalDRL: 3000,
    localDRL: 2800,
    hospitalAvg: 2650,
    exceedCount: 18,
    totalCount: 156,
    compliancePercent: 88.5,
    unit: "mGy路m虏",
  },
  {
    modality: "MG",
    examType: "乳腺钼靶",
    nationalDRL: 6,
    localDRL: 5.5,
    hospitalAvg: 5.2,
    exceedCount: 3,
    totalCount: 324,
    compliancePercent: 99.1,
    unit: "mGy",
  },
];

// 剂量控制图数据
export const controlChartData: ControlChartPoint[] = [
  { date: "04-25", mean: 22.5, ucl: 32, lcl: 12, range: 8.5, rangeUcl: 15 },
  { date: "04-26", mean: 21.8, ucl: 32, lcl: 12, range: 7.2, rangeUcl: 15 },
  { date: "04-27", mean: 24.2, ucl: 32, lcl: 12, range: 9.8, rangeUcl: 15 },
  { date: "04-28", mean: 20.5, ucl: 32, lcl: 12, range: 6.5, rangeUcl: 15 },
  { date: "04-29", mean: 18.9, ucl: 32, lcl: 12, range: 5.8, rangeUcl: 15 },
  { date: "04-30", mean: 23.1, ucl: 32, lcl: 12, range: 8.2, rangeUcl: 15 },
  { date: "05-01", mean: 19.5, ucl: 32, lcl: 12, range: 6.2, rangeUcl: 15 },
];

// 儿童协议优化建议
export const pediatricProtocols: PediatricProtocol[] = [
  {
    ageGroup: "placeholder",
    weightMin: 5,
    weightMax: 15,
    recommendedKVP: 80,
    recommendedMAS: 60,
    doseReductionFactor: 0.4,
    protocolName: "placeholder",
  },
  {
    ageGroup: "placeholder",
    weightMin: 15,
    weightMax: 30,
    recommendedKVP: 100,
    recommendedMAS: 80,
    doseReductionFactor: 0.6,
    protocolName: "placeholder",
  },
  {
    ageGroup: "placeholder",
    weightMin: 30,
    weightMax: 50,
    recommendedKVP: 120,
    recommendedMAS: 100,
    doseReductionFactor: 0.7,
    protocolName: "青少年头部CT",
  },
  {
    ageGroup: "placeholder",
    weightMin: 5,
    weightMax: 15,
    recommendedKVP: 80,
    recommendedMAS: 40,
    doseReductionFactor: 0.35,
    protocolName: "placeholder",
  },
  {
    ageGroup: "placeholder",
    weightMin: 15,
    weightMax: 30,
    recommendedKVP: 100,
    recommendedMAS: 50,
    doseReductionFactor: 0.5,
    protocolName: "placeholder",
  },
  {
    ageGroup: "placeholder",
    weightMin: 30,
    weightMax: 50,
    recommendedKVP: 120,
    recommendedMAS: 70,
    doseReductionFactor: 0.65,
    protocolName: "青少年胸部CT",
  },
];


