export type ExportConfig = { format: string; quality?: number; };
export type ExportJob = { id: string; status: string; progress: number; };
export type BrandingConfig = {
  siteName: string;
  footerText: string;
  primaryColor: string;
  secondaryColor: string;
  fontFamily: string;
  showWatermark: boolean;
  showQrCode: boolean;
  showSignature: boolean;
  logoDataUrl?: string;
  contactEmail?: string;
  contactPhone?: string;
};
export type DicomDeIdConfig = { removeFields?: string[]; };
export type EmailConfig = { host: string; port: number; };
export type EmailMessage = {
  to: string[];
  cc?: string[];
  bcc?: string[];
  from?: string;
  subject?: string;
  body?: string;
  html?: string;
  isHtml?: boolean;
  attachments?: EmailAttachment[];
};
export type FtpConfig = { host: string; username: string; password: string; };
export type PptxTemplate = { id: string; name: string; };
export type QrConfig = { size: number; correction: string; };
export type ScheduleConfig = { cron: string; timezone: string; };
export type TemplateConfig = { id: string; content: string; };
export type WatermarkConfig = { text: string; opacity: number; };

export type BulkExportResult = any;
export type ExportProgressInfo = any;
export type ExportFormatV2 = any;
export type DicomDeIdOptions = any;
export type EmailAttachment = any;
export type ExportResult = any;
export type PptxSlide = any;
export type PptxExportOptions = any;
export type QrStampOptions = any;
export type ScheduleJob = any;
export type ScheduleFrequency = any;
export type ReportQuery = any;
export type WatermarkOptions = any;
export type PrintColumn = any;
export type BulkExportOptions = any;
export type BulkExportItemResult = any;
export type ExportProgressEvent = any;
export type ExportStatus = any;
export type EncryptedPdfOptions = any;
