// [G005 v3.0.6.11-101 Wave 6A F11] 报告质控规则引擎 — 内置规则库 (18 条, 放射专业)
import type { QualityRule } from './report-rules.types'

export const BUILTIN_RULES: QualityRule[] = [
  {
    id: 'rule-b-001',
    code: 'RR-MISSING-01',
    name: '报告结论为空',
    type: 'missing_field',
    severity: 'error',
    description: '报告结论 (conclusion) 为空, 无法向临床传达诊断意见',
    condition: { field: 'conclusion', operator: 'empty', value: '' },
    suggestion: '请补充报告结论, 例如: 双肺未见明显实质性病变, 建议定期随访。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-002',
    code: 'RR-MISSING-02',
    name: '影像所见为空',
    type: 'missing_field',
    severity: 'error',
    description: '影像所见 (findings) 为空, 报告缺乏描述性依据',
    condition: { field: 'findings', operator: 'empty', value: '' },
    suggestion: '请描述影像所见, 包括形态、密度/信号、边缘、与邻近结构关系。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-003',
    code: 'RR-MISSING-03',
    name: '诊断结论为空',
    type: 'missing_field',
    severity: 'error',
    description: '诊断结论 (diagnosis) 为空, 未给出诊断意见',
    condition: { field: 'diagnosis', operator: 'empty', value: '' },
    suggestion: '请补充诊断结论, 如: 右肺上叶磨玻璃结节, 建议随访复查。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-004',
    code: 'RR-MISSING-04',
    name: '随访建议缺失',
    type: 'missing_field',
    severity: 'error',
    description: '结论含"随访/复查"等指向时, 未提供随访建议',
    condition: {
      field: 'recommendations',
      operator: 'empty',
      value: '',
      when: {
        field: 'conclusion',
        operator: 'contains',
        value: '随访|复查|定期|必要时',
      },
    },
    suggestion: '补充随访建议, 例如: 建议 3-6 个月后复查 CT 观察结节变化。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-005',
    code: 'RR-MISSING-05',
    name: '病灶未描述部位',
    type: 'missing_field',
    severity: 'warning',
    description: '所见含病灶/结节/占位, 但未描述具体解剖部位',
    condition: {
      field: 'findings',
      operator: 'not_contains',
      value: '肺|肝|肾|脾|胰|胆|胃|肠|骨|脑|心|胸|腹|盆腔|甲状腺|乳腺|子宫|前列腺|淋巴结|纵隔|椎体|肩|髋|膝|踝|肘|腕|窦|咽|喉|气管|食管|肾上腺|卵巢|膀胱|输尿管',
      when: {
        field: 'findings',
        operator: 'contains',
        value: '结节|占位|肿块|病灶|囊肿|钙化',
      },
    },
    suggestion: '请标注病灶具体部位, 如: 左肺上叶尖后段见结节影。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-006',
    code: 'RR-SIDE-01',
    name: '左右侧别缺失',
    type: 'missing_field',
    severity: 'warning',
    description: '病灶/结节描述未明确左右侧别, 影响手术定位与疗效评估',
    condition: {
      field: 'findings',
      operator: 'not_contains',
      value: '左|右|双侧',
      when: {
        field: 'findings',
        operator: 'contains',
        value: '结节|肿块|病灶|囊肿|钙化|磨玻璃',
      },
    },
    suggestion: '补充左右侧别, 如: 右肺下叶见 5mm 小结节影。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-007',
    code: 'RR-MISSING-06',
    name: '增强对比剂信息缺失',
    type: 'missing_field',
    severity: 'warning',
    description: '增强扫描未描述对比剂用量/类型/过敏反应',
    condition: {
      field: 'findings',
      operator: 'not_contains',
      value: '对比剂|造影剂|增强后|碘海醇|钆',
      when: {
        field: 'findings',
        operator: 'contains',
        value: '增强扫描|增强后',
      },
    },
    suggestion: '补充对比剂信息: 名称、用量、注射方式及有无不良反应。',
    builtIn: true,
    enabled: true,
    examTypes: ['CT', 'MRI', 'MR'],
  },
  {
    id: 'rule-b-008',
    code: 'RR-TERM-01',
    name: '口语化模糊表述',
    type: 'terminology',
    severity: 'warning',
    description: '报告使用口语化/模糊表述, 不符合书写规范',
    condition: { field: 'fullText', operator: 'contains', value: '好像|似乎|说不清|不知道|不好说|大概是' },
    suggestion: '使用确定性术语, 如"考虑""显示""未见明确异常"。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-009',
    code: 'RR-TERM-02',
    name: '模糊诊断表述提示',
    type: 'terminology',
    severity: 'info',
    description: '诊断结论含"考虑/可能/不除外", 建议给出随访策略',
    condition: { field: 'conclusion', operator: 'contains', value: '考虑|可能|不除外|待排' },
    suggestion: '模糊诊断建议配套随访建议或进一步检查意见。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-010',
    code: 'RR-TERM-03',
    name: '非规范缩略语',
    type: 'terminology',
    severity: 'warning',
    description: '使用非规范缩略语 (如肺CA), 应使用规范术语',
    condition: { field: 'fullText', operator: 'regex', value: '肺\\s*CA|肺Ca|胃Ca|肝Ca' },
    suggestion: '使用规范术语: 肺癌/胃癌/肝癌。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-011',
    code: 'RR-UNIT-01',
    name: '数值无单位',
    type: 'unit',
    severity: 'warning',
    description: '病灶尺寸等数值后未标注单位 (mm/cm/HU 等)',
    condition: {
      field: 'findings',
      operator: 'regex',
      value: '(?:大小约|直径约|长约|宽约|厚约|约)\\s*\\d+(?:\\.\\d+)?(?!\\s*(?:mm|cm|mm²|cm²|mm³|HU|ml|mL|mg|g|μg|ug|IU|L|kPa|mmHg|℃|°|sec|min))',
    },
    suggestion: '为数值补充法定计量单位, 如: 大小约 5mm。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-012',
    code: 'RR-NUM-01',
    name: '病灶尺寸超常规范围',
    type: 'numeric_reasonability',
    severity: 'error',
    description: '结节/肿块尺寸超过 400mm, 数值可能录入错误',
    condition: { field: 'findings', operator: 'numeric_over', value: '400mm' },
    suggestion: '请复核病灶尺寸数值及单位, 疑似录入错误。',
    builtIn: true,
    enabled: true,
    examTypes: ['CT', 'MR', 'MRI'],
  },
  {
    id: 'rule-b-013',
    code: 'RR-NUM-02',
    name: 'CT 值超合理范围',
    type: 'numeric_reasonability',
    severity: 'error',
    description: 'CT 值 (HU) 超过 3000, 超出临床合理范围',
    condition: { field: 'findings', operator: 'numeric_over', value: '3000HU' },
    suggestion: '请复核 CT 值描述, 常规组织密度范围 -1000 ~ +3000HU。',
    builtIn: true,
    enabled: true,
    examTypes: ['CT'],
  },
  {
    id: 'rule-b-014',
    code: 'RR-CONSIST-01',
    name: '结论与所见不一致',
    type: 'missing_field',
    severity: 'error',
    description: '所见描述病灶, 但诊断结论未体现对应病灶意见',
    condition: {
      field: 'diagnosis',
      operator: 'not_contains',
      value: '结节|占位|肿块|病灶|囊肿|钙化|积液',
      when: {
        field: 'findings',
        operator: 'contains',
        value: '结节|占位|肿块|病灶|囊肿|钙化|积液',
      },
    },
    suggestion: '诊断结论需与影像所见一致, 请补全病灶结论描述。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-015',
    code: 'RR-DUP-01',
    name: '重复表述',
    type: 'duplicate',
    severity: 'info',
    description: '同一短语在结论中重复出现 ≥2 次, 建议精简',
    condition: { field: 'conclusion', operator: 'dup_count', value: 2 },
    suggestion: '删除重复短语, 精简结论表述。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-016',
    code: 'RR-LEN-01',
    name: '影像所见过短',
    type: 'length_range',
    severity: 'warning',
    description: '影像所见少于 20 字, 描述不完整',
    condition: { field: 'findings', operator: 'length_lt', value: 20 },
    suggestion: '补充所见描述: 密度/信号、形态、边缘、增强表现等。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-017',
    code: 'RR-LEN-02',
    name: '结论过长',
    type: 'length_range',
    severity: 'info',
    description: '结论超过 300 字, 建议分层精简表达',
    condition: { field: 'conclusion', operator: 'length_gte', value: 300 },
    suggestion: '结论建议控制在 300 字以内, 按阳性-阴性-建议分层。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
  {
    id: 'rule-b-018',
    code: 'RR-CRIT-01',
    name: '危急征象提示确认',
    type: 'terminology',
    severity: 'info',
    description: '所见含危急征象关键词, 需确认危急值上报流程',
    condition: { field: 'findings', operator: 'contains', value: '气胸|脑出血|主动脉夹层|大量心包积液|肠梗阻|脾破裂|张力性' },
    suggestion: '请确认已执行危急值报告流程 (口头通知 + 30 分钟内复核)。',
    builtIn: true,
    enabled: true,
    examTypes: [],
  },
]

export const BUILTIN_RULESET_SEEDS: Array<{
  id: string
  name: string
  description: string
  examTypes: string[]
  ruleIds: string[]
}> = [
  {
    id: 'rs-ct-chest',
    name: 'CT 胸部规则集',
    description: '胸部 CT 报告质控: 部位/侧别/尺寸/单位/随访完整性',
    examTypes: ['CT'],
    ruleIds: [
      'rule-b-001',
      'rule-b-002',
      'rule-b-003',
      'rule-b-004',
      'rule-b-005',
      'rule-b-006',
      'rule-b-007',
      'rule-b-011',
      'rule-b-012',
      'rule-b-013',
      'rule-b-014',
      'rule-b-016',
    ],
  },
  {
    id: 'rs-mri-head',
    name: 'MRI 头颅规则集',
    description: '头颅 MRI 报告质控: 侧别/术语/数值合理性',
    examTypes: ['MRI', 'MR'],
    ruleIds: [
      'rule-b-001',
      'rule-b-002',
      'rule-b-003',
      'rule-b-004',
      'rule-b-005',
      'rule-b-006',
      'rule-b-008',
      'rule-b-009',
      'rule-b-011',
      'rule-b-012',
      'rule-b-014',
      'rule-b-015',
    ],
  },
  {
    id: 'rs-dr-routine',
    name: 'DR 常规规则集',
    description: 'DR 平片报告质控: 必填字段/结论一致性',
    examTypes: ['DR', 'X-ray'],
    ruleIds: [
      'rule-b-001',
      'rule-b-002',
      'rule-b-003',
      'rule-b-004',
      'rule-b-005',
      'rule-b-006',
      'rule-b-014',
      'rule-b-016',
    ],
  },
]
