// [G005 W8-Report] 分级审核规则 — 内置规则库 (放射分级审核, seed)
import type { ReviewTierRule } from './review-tier.types'

export const BUILTIN_REVIEW_TIER_RULES: ReviewTierRule[] = [
  {
    id: 'rtier-b-001',
    code: 'RT-CRIT-01',
    name: '危急征象双签',
    description: '存在危急征象 (气胸/主动脉夹层/脑出血等) → 需终核 + 双签',
    tier: 'dual-sign',
    enabled: true,
    priority: 100,
    when: { isCritical: true },
    reason: '危急征象报告须终核并双人签名',
  },
  {
    id: 'rtier-b-002',
    code: 'RT-SEV-CRIT',
    name: '严重级别危急',
    description: 'severity=critical → 双签',
    tier: 'dual-sign',
    enabled: true,
    priority: 95,
    when: { severities: ['critical'] },
    reason: '严重级别为危急, 须双签',
  },
  {
    id: 'rtier-b-003',
    code: 'RT-RADS-5',
    name: 'RADS 5 类双阅',
    description: 'RADS 分类 >= 5 (高度可疑恶性) → 双阅',
    tier: 'dual-read',
    enabled: true,
    priority: 90,
    when: { radsCategoryGte: 5 },
    reason: 'RADS 5 类高度可疑, 须双人阅片',
  },
  {
    id: 'rtier-b-004',
    code: 'RT-RADS-4',
    name: 'RADS 4 类双签',
    description: 'RADS 分类 >= 4 (可疑恶性) → 双签',
    tier: 'dual-sign',
    enabled: true,
    priority: 80,
    when: { radsCategoryGte: 4 },
    reason: 'RADS 4 类可疑, 须双签',
  },
  {
    id: 'rtier-b-005',
    code: 'RT-RADS-3',
    name: 'RADS 3 类终核',
    description: 'RADS 分类 >= 3 (可能良性) → 终核',
    tier: 'final',
    enabled: true,
    priority: 70,
    when: { radsCategoryGte: 3 },
    reason: 'RADS 3 类须终核',
  },
  {
    id: 'rtier-b-006',
    code: 'RT-SEV-HIGH',
    name: '严重级别高终核',
    description: 'severity=high → 终核',
    tier: 'final',
    enabled: true,
    priority: 60,
    when: { severities: ['high'] },
    reason: '严重级别高, 须终核',
  },
  {
    id: 'rtier-b-007',
    code: 'RT-AUTHOR-JR',
    name: '低资历医师报告加严',
    description: '作者为住院医师 (resident) → 终核; 结合危急/高 RADS 可升为双签',
    tier: 'final',
    enabled: true,
    priority: 50,
    when: { authorSeniorityIn: ['resident'] },
    reason: '低资历医师报告须上级终核',
  },
  {
    id: 'rtier-b-008',
    code: 'RT-MOD-HIGH',
    name: '增强/高危模态终核',
    description: 'CT/MRI 增强或急诊类模态 → 终核',
    tier: 'final',
    enabled: true,
    priority: 40,
    when: { modalities: ['CT', 'MRI', 'MR'] },
    reason: 'CT/MRI 报告须终核',
  },
  {
    id: 'rtier-b-009',
    code: 'RT-DEFAULT',
    name: '常规初核',
    description: '无更严格规则命中时的默认最低审核等级: 初核',
    tier: 'initial',
    enabled: true,
    priority: 1,
    when: {},
    reason: '常规报告默认初核',
  },
]
